Settings product template list
stock2shop/console_v2 pull request #120
Opened 2023-05-05 07:31 UTC by aStarlikeMine

In the settings menu, list the existing product templates.
Re-use existing code from Settings > Users by creating a generic layout component for Settings.

_Notes:_

- It is visually not exactly as per Zeplin as we have based the component on the existing Settings > Users component, which we assume has been approved
- Search has been removed as currently the endpoint does not support it, and in-memory search is more time that's not necessary at the moment. 

Zeplin:
![image](https://user-images.githubusercontent.com/113701230/236399083-98308590-fb76-4e9f-ab64-5b3f902e4fb6.png)

Implementation:
![image](https://user-images.githubusercontent.com/113701230/236398999-23bbab79-9cae-4251-9170-1ef9ea88b337.png)

2023-05-09 09:07 UTC, laraDuPreezKrs approved these changes

2023-05-09 09:46 UTC, justinengle-krs requested changes
Still a few comments & then please run the chromatic build

2023-05-10 06:52 UTC, aStarlikeMine commented on src/components/Settings/SettingsLayout.svelte
I thought about this but since it's used in the ProductTemplates and Users (and those have stories), is it worth it?

2023-05-10 08:47 UTC, aStarlikeMine commented on src/components/Settings/SettingsCheckbox.svelte
I think we didn't go far enough with this checkbox. We created the SettingsCheckbox in order not to repeat code and  didn't reuse the existing CheckboxCell because  Users component in Settings didn't. However I've had a look and it's possible to reuse it, so I've done that. 

Also, how is the checkbox going to be used in the future? I see Settings>Users also doesn't have an implementation yet either

2023-05-10 12:55 UTC, justinengle-krs submitted a review, later dismissed

2023-05-11 10:04 UTC, matthampton-stock2shop requested changes

2023-05-11 10:04 UTC, matthampton-stock2shop commented on src/components/form/Btn.svelte
> +  export let Prefix: SvelteComponent<void> | undefined = undefined;
Are these changes doing anything? Why are they needed?

2023-05-11 10:04 UTC, matthampton-stock2shop commented on src/lib/constants.ts
> +export const prependProduct = 'product_';
I think I'd prefer a constant name that follows the traditional all caps convention, but also that indicates the context a bit e.g. PRODUCT_META_TEMPLATE_PREFIX

2023-05-11 10:21 UTC, aStarlikeMine commented on src/components/form/Btn.svelte
> +  export let Prefix: SvelteComponent<void> | undefined = undefined;
Not needed, I'll revert. Can't remember why it was added

2023-05-11 12:13 UTC, matthampton-stock2shop commented
@aStarlikeMine Can I ask for a couple of things here - then I'll do a last look over:

- [ ] Merge origin/master and resolve conflicts
- [ ] Run the chromatic build and paste a link in here for me to review

2023-05-11 12:52 UTC, aStarlikeMine commented
@matthampton-stock2shop https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=68

2023-05-11 13:07 UTC, matthampton-stock2shop requested changes

2023-05-11 13:07 UTC, matthampton-stock2shop commented on src/components/Settings/Users.svelte
> +<SettingsLayout
It seems like we might have lost something in this refactor: see https://www.chromatic.com/test?appId=63ef6cddab1dec384359e1cd&id=645ce40d66aafe75a7e544c7

2023-05-12 06:32 UTC, aStarlikeMine commented on src/components/Settings/Users.svelte
> +<SettingsLayout
Sorry about that. I was already leaving work late so I didn't have time to check the results of the build. 
With adding a model for the inlineNotification, there was a check that was missed. Fixed now. And here's the new link: https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=69

It says there are no visual changes... ?

2023-05-12 06:53 UTC, matthampton-stock2shop commented on src/components/Settings/Users.svelte
> +<SettingsLayout
thanks, @aStarlikeMine !

> It says there are no visual changes... ?

I that's cos I already approved the two new screens for the previous build ...

2023-05-12 06:53 UTC, matthampton-stock2shop approved these changes

2023-05-12 06:54 UTC, merged