Polishing up order listing screen with Facets
stock2shop/console_v2 pull request #125
Opened 2023-05-08 15:32 UTC by justinengle-krs

Zeplin:
![image](https://user-images.githubusercontent.com/125956275/236865485-46c29847-bd39-4c36-84ea-27d5a8bbc6e0.png)
Implementation:
![image](https://user-images.githubusercontent.com/125956275/236866009-92fd9963-4465-49f1-9bb3-bc3fb5ec42d9.png)

2023-05-16 08:36 UTC, casperlotter submitted a review, later dismissed

2023-05-16 13:43 UTC, matthampton-stock2shop requested changes
Not done with the review yet - but need to leave now - so will pick this up tomorrow...

@justinengle-krs Could you run chromatic on this one? Thanks!

2023-05-16 13:43 UTC, matthampton-stock2shop commented on src/components/Orders/ChannelBucket.svelte
> +    if (!dependencyContainer) console.error('Ensure order-col-dependency context is set.');
Is this debugging code?

2023-05-16 13:43 UTC, matthampton-stock2shop commented on src/components/Orders/ChannelCell.svelte
> +  $: channelName = channels.find((c) => c.id.toString() == data.channel_id)?.description ?? '-';
Same comment here RE loading / isError

2023-05-17 11:26 UTC, justinengle-krs commented
> Not done with the review yet - but need to leave now - so will pick this up tomorrow...
> 
> @justinengle-krs Could you run chromatic on this one? Thanks!

https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=83

2023-05-17 12:06 UTC, matthampton-stock2shop commented on src/stories/components/70-Orders/20-OrdersGridRow.stories.svelte
> +  const columnsIdToShow = ['id', 'created', 'channel_id', 'status', 'total_display'];
I know this is just a test really, but could we keep the channel_order_code and add in the channel_id next to it?

2023-05-17 12:07 UTC, matthampton-stock2shop commented on src/routes/Orders.svelte
> +<OrdersList />
Could we add a storybook screen for this route with a bunch of orders in it?

2023-05-17 12:07 UTC, matthampton-stock2shop requested changes
@justinengle-krs Just a couple of things - and sorry for the back-and-forth on that error thing

2023-05-17 12:09 UTC, matthampton-stock2shop commented on src/components/Orders/ChannelBucket.svelte
> +    if (!dependencyContainer) console.error('Ensure order-col-dependency context is set.');
@justinengle-krs What is this about? Do we need it? I feel like I'd rather have the thing raise an exception if it doesn't have the context that it needs - cos that would be a bug, right? 

Or just fail later when it gets a null reference ... (i.e. not even check - just believe!)

2023-05-18 11:07 UTC, justinengle-krs commented
> @justinengle-krs Just a couple of things - and sorry for the back-and-forth on that error thing

https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=86

2023-05-18 11:16 UTC, matthampton-stock2shop approved these changes

2023-05-18 11:16 UTC, merged