Casper krs/product dynamic pricing
stock2shop/console_v2 pull request #130
Opened 2023-05-18 11:33 UTC by casperlotter

2023-05-19 09:03 UTC, justinengle-krs commented on src/components/PricingContracts/AddPricingContractModal.svelte
> +  let index = ElasticSearchIndex.CUSTOMERS;
this is maybe a bit of a personal preference but I prefer something like this as a ternary. A bit more 'declarative' in a sense. But I dont have a strong reason to change it.

`let index =  $contract.forCustomer() ? ElasticSearchIndex.CUSTOMERS : ElasticSearchIndex.PRODUCTS;`

2023-05-19 09:04 UTC, justinengle-krs commented on src/components/PricingContracts/DynamicPricing.svelte
> +  let entity = customerId ? 'product' : 'customer';
does this need to be a VM property? or can it by scoped to where it's used

2023-05-19 09:07 UTC, justinengle-krs commented on src/repos/product-meta-repo.ts
> +interface SystemProductMeta {
just to keep the standards the same, can these interfaces sit in our model folder? and repo is just the api calls

2023-05-19 12:05 UTC, justinengle-krs submitted a review, later dismissed

2023-05-22 13:41 UTC, matthampton-stock2shop requested changes

2023-05-22 13:41 UTC, matthampton-stock2shop commented on src/stories/routes/25-ProductContract.stories.svelte
> -  // eslint-disable-next-line import/no-extraneous-dependencies
https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=96

I did a chromatic run and made a couple of comments

2023-05-22 13:41 UTC, matthampton-stock2shop commented on src/models/meta.ts
> +  customer_id?: string;
Is this optional?

2023-05-22 13:41 UTC, matthampton-stock2shop commented on src/models/meta.ts
> +  product_id?: string;
And this?

2023-05-23 06:59 UTC, matthampton-stock2shop approved these changes

2023-05-23 06:59 UTC, merged