Product details single variant
stock2shop/console_v2 pull request #132
Opened 2023-05-19 08:11 UTC by casperlotter

2023-05-24 07:52 UTC, justinengle-krs requested changes

2023-05-24 07:52 UTC, justinengle-krs commented on src/routes/Product.svelte
> +  <div>Loading customer data...</div>
should be product data

2023-05-24 07:52 UTC, justinengle-krs commented on src/routes/Product.svelte
> +  <div>Error loading customer data.</div>
same here

2023-05-24 07:52 UTC, justinengle-krs commented on src/routes/Product.svelte
> +      <div class="flex w-full product-details">
why product-details class?

2023-05-24 13:11 UTC, justinengle-krs submitted a review, later dismissed

2023-05-24 13:42 UTC, matthampton-stock2shop requested changes
hi @casperlotter 

I haven't got to the code yet - but there are some things showing up in the chromatic that look possibly accidental.. Would you mind have a look?

2023-05-24 13:42 UTC, matthampton-stock2shop commented on package.json
>      "format": "prettier --write ./src/**/*.{css,ts,svelte}",
Some comments on the chromatic build:

https://www.chromatic.com/test?appId=63ef6cddab1dec384359e1cd&id=646dfdf618bbe952d458932b

2023-05-24 13:42 UTC, matthampton-stock2shop commented on package.json
>      "format": "prettier --write ./src/**/*.{css,ts,svelte}",
https://www.chromatic.com/test?appId=63ef6cddab1dec384359e1cd&id=646dfdf618bbe952d458932c

2023-05-24 13:42 UTC, matthampton-stock2shop commented on package.json
>      "format": "prettier --write ./src/**/*.{css,ts,svelte}",
https://www.chromatic.com/test?appId=63ef6cddab1dec384359e1cd&id=646dfdf618bbe952d4589372

2023-05-24 13:42 UTC, matthampton-stock2shop commented on package.json
>      "format": "prettier --write ./src/**/*.{css,ts,svelte}",
Those are all the same thing, I think

2023-05-25 09:19 UTC, casperlotter commented on package.json
>      "format": "prettier --write ./src/**/*.{css,ts,svelte}",
@matthampton-stock2shop I pushed updates for this. Not sure how the checkbox went missing since this code did not touch it. I had to remove the border-transparent property for it to display again.

2023-05-25 10:30 UTC, matthampton-stock2shop requested changes

2023-05-25 10:30 UTC, matthampton-stock2shop commented on src/components/Product/ProductDetails.svelte
> +        productVersionControlled.workingCopy.source_id,
And do you need '$'s here? Not 100% sure...

2023-05-25 10:30 UTC, matthampton-stock2shop commented on src/components/Product/ProductDetails.svelte
> +  const dragPhotoSlider = (e: MouseEvent) => {
Would it be possible to make use of some of the tailwind scrolling classes here? (I am not sure - but it maybe there is something there for us) - and I feel a little uncomfortable about implementing some sort of scrolling behaviour in javascript ...

https://tailwindcss.com/docs/scroll-behavior

But maybe it can't be helped...

@justinengle-krs Do you know?

2023-05-25 10:30 UTC, matthampton-stock2shop commented on src/routes/Product.svelte
> +      if (!data) return;
Is this going to lead to a permanently load spinner? (cos productVersionControlled will stay null - which is used by ProductMaster to figure out it is is loading still)

Isn't this an error condition rather?

2023-05-25 11:07 UTC, casperlotter commented on src/components/Product/ProductDetails.svelte
> +  const dragPhotoSlider = (e: MouseEvent) => {
@matthampton-stock2shop Tailwind does not give us what we need. We will need js here. But I will create a component from this functionality instead.

2023-05-29 10:40 UTC, matthampton-stock2shop commented
New build: https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=117

2023-05-29 10:42 UTC, matthampton-stock2shop approved these changes

2023-05-29 10:42 UTC, merged