Justin krs/images import progress
stock2shop/console_v2 pull request #174
Opened 2023-06-29 16:00 UTC by justinengle-krs

Implements the matching of images to the product SKUS:

![image](https://github.com/stock2shop/console_v2/assets/125956275/ae9dd716-9d2d-4e00-b310-89c6a7100ce1)

Zeplin:
![image](https://github.com/stock2shop/console_v2/assets/125956275/91e32159-1126-47d3-88b8-8c712b6dcb19)

2023-06-30 07:34 UTC, casperlotter approved these changes

2023-06-30 08:12 UTC, mannyqi commented
## Styling & Functionality
1. "Add Rule" button uses incorrect font-size and padding (or width & height)
<img width="363" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/7f3302e9-cbaf-4f0e-b755-5ddde986d7a8">

2. The "Remove All" and "Upload All" buttons are small than in design
<img width="434" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/ee4d6086-a51e-4a2c-b279-b98d610b3422">

3. There should be `16px` spacing between buttons
<img width="338" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/4a43ed66-29b6-4793-9f25-303dc0cfaf89">

4. Table headers should be `11px` and not `13px`
<img width="1500" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/676cc65e-8bbc-4244-ae92-14a0ac70203d">

5. Each row should have `24px` padding to the left and right
<img width="1008" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/bf94d47d-41eb-435c-b621-dfbdb7bb740b">

6. When uploading a single image exceeding the max upload size (5mb), then an appropriate error message is displayed. However, when uploading multiple images at the same time, then large images are simply ignored (no error message is displayed) and the rest is added to the queue. Perhaps these files should still be included in a list but with a status of "Too Large" or maybe instead of having the message "Failed to match product, image ignored!", have "File size is too large. Max 5MB allowed"?
![image](https://github.com/stock2shop/console_v2/assets/2038721/5fcd1ac9-50fe-4326-9427-2cfe627d5118)

7. Blue text in top-left corner should be `13px`, not `14px`
<img width="1698" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/05af0a26-963f-4679-bcc7-94a4902fdc57">

8. In the zeplin design it looks like the remove and upload buttons are immediately below the list of uploaded files. So I would assume the buttons are pushed down as the list grows. But I think always having it visible at the bottom (like you have it) might be better, but it just needs a white background.
![image](https://github.com/stock2shop/console_v2/assets/2038721/6c4409e8-ca83-43d4-aa51-53ee6395072a)

2023-06-30 08:20 UTC, mannyqi commented
One that I missed:

9. Unsupported file format error message is not styled properly
![image](https://github.com/stock2shop/console_v2/assets/2038721/b38157c2-177f-4f5e-8571-5e4ab14cde95)

2023-06-30 09:21 UTC, justinengle-krs commented
> ## Styling & Functionality
> 1. "Add Rule" button uses incorrect font-size and padding (or width & height)
> 
> <img alt="image" width="363" src="https://user-images.githubusercontent.com/2038721/250015104-7f3302e9-cbaf-4f0e-b755-5ddde986d7a8.png">
> 2. The "Remove All" and "Upload All" buttons are small than in design
> 
> <img alt="image" width="434" src="https://user-images.githubusercontent.com/2038721/250018335-ee4d6086-a51e-4a2c-b279-b98d610b3422.png">
> 3. There should be `16px` spacing between buttons
> 
> <img alt="image" width="338" src="https://user-images.githubusercontent.com/2038721/250018860-4a43ed66-29b6-4793-9f25-303dc0cfaf89.png">
> 4. Table headers should be `11px` and not `13px`
> 
> <img alt="image" width="1500" src="https://user-images.githubusercontent.com/2038721/250019585-676cc65e-8bbc-4244-ae92-14a0ac70203d.png">
> 5. Each row should have `24px` padding to the left and right
> 
> <img alt="image" width="1008" src="https://user-images.githubusercontent.com/2038721/250020264-bf94d47d-41eb-435c-b621-dfbdb7bb740b.png">
> 6. When uploading a single image exceeding the max upload size (5mb), then an appropriate error message is displayed. However, when uploading multiple images at the same time, then large images are simply ignored (no error message is displayed) and the rest is added to the queue. Perhaps these files should still be included in a list but with a status of "Too Large" or maybe instead of having the message "Failed to match product, image ignored!", have "File size is too large. Max 5MB allowed"?
>    ![image](https://user-images.githubusercontent.com/2038721/250021117-5fcd1ac9-50fe-4326-9427-2cfe627d5118.png)
> 7. Blue text in top-left corner should be `13px`, not `14px`
> 
> <img alt="image" width="1698" src="https://user-images.githubusercontent.com/2038721/250025432-05af0a26-963f-4679-bcc7-94a4902fdc57.png">
> 8. In the zeplin design it looks like the remove and upload buttons are immediately below the list of uploaded files. So I would assume the buttons are pushed down as the list grows. But I think always having it visible at the bottom (like you have it) might be better, but it just needs a white background.
>    ![image](https://user-images.githubusercontent.com/2038721/250026586-6c4409e8-ca83-43d4-aa51-53ee6395072a.png)

Regarding some of the buttons -  I am hesitant to change this as the project has predefined and consistent button variants and styles, I don't think we should implement  zeplin pixel perfects if it doesn't align with the other screens? Unless something is way off then we'd need a new variant

The same with the font sizes the app consistently uses the following sizes, and I think we should stick to whichever is the closest, if its within 1px?

```
        smaller: '0.625rem',
        small: '0.688rem',
        regular: '0.813rem',
        big: '1.25rem',
```

Let me know what you think? 
Padding and mis-alignments and things that look off I will resolve though as well as  the functionality issues

2023-06-30 09:35 UTC, mannyqi requested changes
Can we re-apply the rules when switching between the fields as well?

2023-06-30 09:35 UTC, mannyqi commented on src/components/Import/ImportImagesModal.svelte
> +    const matchedProduct = products.find(isMatch);
We can just return the value here instead of creating const

2023-06-30 09:35 UTC, mannyqi commented on src/components/Import/ImportImagesModal.svelte
> +    const esSearch = {
We can just return the value

2023-06-30 09:47 UTC, mannyqi commented
> I am hesitant to change this as the project has predefined and consistent button variants and styles, I don't think we should implement zeplin pixel perfects if it doesn't align with the other screens?
> 
> The same with the font sizes the app consistently uses the following sizes, and I think we should stick to whichever is the closest, if its within 1px?

I was instructed to also check styling, so can't say. Let me try and check with Chris first and get back to you.

2023-06-30 09:52 UTC, justinengle-krs commented
> > I am hesitant to change this as the project has predefined and consistent button variants and styles, I don't think we should implement zeplin pixel perfects if it doesn't align with the other screens?
> > The same with the font sizes the app consistently uses the following sizes, and I think we should stick to whichever is the closest, if its within 1px?
> 
> I was instructed to also check styling, so can't say. Let me try and check with Chris first and get back to you.

Okay no problem. I will get everything else sorted in the meantime

2023-06-30 10:55 UTC, justinengle-krs commented on src/components/Import/ImportImagesModal.svelte
>    import Icon from '../Icons/Icon.svelte';
Done

2023-06-30 10:55 UTC, justinengle-krs commented on src/components/Import/ImportImagesModal.svelte
> +    const matchedProduct = products.find(isMatch);
Done

2023-06-30 10:55 UTC, justinengle-krs commented on src/components/Import/ImportImagesModal.svelte
> +    const esSearch = {
Done

2023-06-30 10:57 UTC, justinengle-krs commented
> > I am hesitant to change this as the project has predefined and consistent button variants and styles, I don't think we should implement zeplin pixel perfects if it doesn't align with the other screens?
> > The same with the font sizes the app consistently uses the following sizes, and I think we should stick to whichever is the closest, if its within 1px?
> 
> I was instructed to also check styling, so can't say. Let me try and check with Chris first and get back to you.

@mannyqi Points 3,5,6,8,9 have been resolved. The table headers are 11px

2023-06-30 12:31 UTC, mannyqi commented
@justinengle-krs happy with all the changes, thanks.

Just one final request - just like in point 6, when uploading a single unsupported file you get the error message like below. I think this should work the same as the others - i.e. unsupported files should still be listed in the queue, but with an appropriate message and status (e.g. Unsupported)

![image](https://github.com/stock2shop/console_v2/assets/2038721/24e65269-2268-4c48-bf02-0dd5ee336cbe)

2023-07-02 20:47 UTC, justinengle-krs commented
> @justinengle-krs happy with all the changes, thanks.
> 
> Just one final request - just like in point 6, when uploading a single unsupported file you get the error message like below. I think this should work the same as the others - i.e. unsupported files should still be listed in the queue, but with an appropriate message and status (e.g. Unsupported)
> 
> ![image](https://user-images.githubusercontent.com/2038721/250088432-24e65269-2268-4c48-bf02-0dd5ee336cbe.png)

@mannyqi Change has been made

2023-07-03 06:38 UTC, mannyqi commented
Thanks @justinengle-krs 
Happy with the change.

2023-07-03 09:03 UTC, mannyqi commented
@justinengle-krs the `Product/DataSync` story is failing to load.

<img width="528" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/30ffc501-d3f8-4ef1-8f86-30edb0463fa3">

2023-07-03 09:04 UTC, justinengle-krs commented
> @justinengle-krs the `Product/DataSync` story is failing to load.
> 
> <img alt="image" width="528" src="https://user-images.githubusercontent.com/2038721/250510345-30ffc501-d3f8-4ef1-8f86-30edb0463fa3.png">

on it

2023-07-03 12:12 UTC, justinengle-krs commented
> > @justinengle-krs the `Product/DataSync` story is failing to load.
> > <img alt="image" width="528" src="https://user-images.githubusercontent.com/2038721/250510345-30ffc501-d3f8-4ef1-8f86-30edb0463fa3.png">
> 
> on it

Fixed @mannyqi

2023-07-04 09:12 UTC, justinengle-krs commented
> @justinengle-krs
> 
> 1. After finishing the uploading of images, you end up with the screen below. When you click the back button in the top-left corner, it closes the modal. If you click "Import Images" again, it opens the same window (after completing upload - 2nd screen) instead of the first step allowing you to upload images.
>    ![image](https://user-images.githubusercontent.com/2038721/250785906-5db01dda-651a-4a98-88e6-03973de92c01.png)
> 
> ![image](https://user-images.githubusercontent.com/2038721/250786510-5ab5695d-cc0d-41ec-adec-6ed4b6fa7c0e.png)

@mannyqi This has been resolved

2023-07-04 14:28 UTC, mannyqi approved these changes

2023-07-05 09:35 UTC, merged