Casper krs/product attributes
stock2shop/console_v2 pull request #197
Opened 2023-07-21 12:16 UTC by casperlotter

Implementation:

![Screenshot 2023-07-21 141336](https://github.com/stock2shop/console_v2/assets/129734011/13bc42e6-413f-4d4b-bf48-cbb21ac157ef)

Zeplin:

![Screenshot 2023-07-21 141528](https://github.com/stock2shop/console_v2/assets/129734011/b6a4ccbc-6154-4249-9158-58048c20af7f)
![Screenshot 2023-07-21 141510](https://github.com/stock2shop/console_v2/assets/129734011/ba23131f-81be-4655-898e-56fae0e85602)

2023-07-25 07:56 UTC, justinengle-krs requested changes

2023-07-25 07:56 UTC, justinengle-krs commented on src/components/Icons/IconCustomer.svelte
> +  export let size: string = '20';
How does this work? The general use case of this size prop is through the <Icon /> element, which passes down a tailwind width. Example:

`<Icon size="smaller" IconComponent={IconCustomer} />`

2023-08-07 11:51 UTC, matthampton-stock2shop requested changes

2023-08-07 11:51 UTC, matthampton-stock2shop commented on src/components/Icons/IconUnlock.svelte
> +<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
(Maybe not related to this pull request - but noting it)

When trying to manage a template, all of the types are greyed out for existing template attributes:

![image](https://github.com/stock2shop/console_v2/assets/124143173/3e1a12fd-486f-4237-a6bb-2e0cc5615503)

If I add a new one I can choose the type.

2023-08-07 11:51 UTC, matthampton-stock2shop commented on src/components/Icons/IconUnlock.svelte
> +  <path
The new screen does not seem to consider the type of the attributes from a template:

![image](https://github.com/stock2shop/console_v2/assets/124143173/0513911f-6da9-48d7-8214-c3a1e7be1017)

This one is supposed to have some number ones and some drop-down:

```
{
    "system_meta_template": [
        {
            "id": 700,
            "client_id": 21,
            "created": "2018-06-21 07:46:53",
            "modified": "2023-01-23 11:56:08",
            "name": "product_Laptop",
            "key": "Promotion",
            "default": "",
            "description": "Promotion Status",
            "type": "dropdown",
            "required": 0,
            "values": [
                {
                    "id": "2",
                    "client_id": "21",
                    "created": "2018-06-21 07:47:35",
                    "modified": "2018-06-21 07:47:35",
                    "metatemplate_id": "700",
                    "key": "End of Range",
                    "value": "End of Range"
                },
                {
                    "id": "1",
                    "client_id": "21",
                    "created": "2018-06-21 07:47:12",
                    "modified": "2018-06-21 07:47:35",
                    "metatemplate_id": "700",
                    "key": "Winter Special",
                    "value": "Winter Special"
                }
            ]
        },
        {
            "id": 701,
            "client_id": 21,
            "created": "2018-06-21 07:48:49",
            "modified": "2023-01-23 11:56:08",
            "name": "product_Laptop",
            "key": "CPU",
            "default": "",
            "description": "Processing Power",
            "type": "dropdown",
            "required": 0,
            "values": [
                {
                    "id": "3",
                    "client_id": "21",
                    "created": "2018-06-21 07:49:10",
                    "modified": "2018-06-21 07:49:17",
                    "metatemplate_id": "701",
                    "key": "2.5ghz",
                    "value": "2.5ghz"
                },
                {
                    "id": "4",
                    "client_id": "21",
                    "created": "2018-06-21 07:49:17",
                    "modified": "2018-06-21 07:49:17",
                    "metatemplate_id": "701",
                    "key": "2.7ghz",
                    "value": "2.7ghz"
                }
            ]
        },
        {
            "id": 702,
            "client_id": 21,
            "created": "2018-06-21 07:51:29",
            "modified": "2023-01-23 11:56:08",
            "name": "product_Laptop",
            "key": "Num Pad",
            "default": "false",
            "description": "Number pad on right?",
            "type": "boolean",
            "required": 0,
            "values": []
        },
        {
            "id": 1314,
            "client_id": 21,
            "created": "2018-07-31 15:00:07",
            "modified": "2023-01-23 11:56:08",
            "name": "product_Laptop",
            "key": "Screen Size",
            "default": "",
            "description": "",
            "type": "dropdown",
            "required": 0,
            "values": [
                {
                    "id": "5812",
                    "client_id": "21",
                    "created": "2018-07-31 15:00:15",
                    "modified": "2018-07-31 15:00:19",
                    "metatemplate_id": "1314",
                    "key": "15 inch",
                    "value": "15 inch"
                },
                {
                    "id": "5813",
                    "client_id": "21",
                    "created": "2018-07-31 15:00:19",
                    "modified": "2018-07-31 15:00:19",
                    "metatemplate_id": "1314",
                    "key": "17 inch",
                    "value": "17 inch"
                }
            ]
        },
        {
            "id": 1361,
            "client_id": 21,
            "created": "2018-08-06 11:43:45",
            "modified": "2023-01-23 11:56:08",
            "name": "product_Laptop",
            "key": "Memory",
            "default": "",
            "description": "",
            "type": "dropdown",
            "required": 1,
            "values": [
                {
                    "id": "6225",
                    "client_id": "21",
                    "created": "2018-08-06 11:43:54",
                    "modified": "2019-04-24 12:16:15",
                    "metatemplate_id": "1361",
                    "key": "2gb",
                    "value": "2gb"
                },
                {
                    "id": "6226",
                    "client_id": "21",
                    "created": "2018-08-06 11:43:59",
                    "modified": "2019-04-24 12:16:15",
                    "metatemplate_id": "1361",
                    "key": "4gb",
                    "value": "4gb"
                }
            ]
        }
    ]
}
```

2023-08-07 11:51 UTC, matthampton-stock2shop commented on src/components/Icons/IconUnlock.svelte
> +    clip-rule="evenodd"
The save changes button gets squished if the title is long:

![image](https://github.com/stock2shop/console_v2/assets/124143173/d93525c5-c4ad-4c3b-86bd-e0a338985f10)

2023-08-07 11:51 UTC, matthampton-stock2shop commented on src/components/Icons/IconUnlock.svelte
> +  <path
Is this meant to work?

2023-08-11 13:02 UTC, casperlotter commented on src/components/Icons/IconCustomer.svelte
> +  export let size: string = 'smaller';
@justinengle-krs ProductMaster renders the slot in an overflow-y-auto wrapper. Let me know if you have any suggestions for the best way forward.

2023-08-14 07:43 UTC, casperlotter commented on src/components/Icons/IconUnlock.svelte
> +    clip-rule="evenodd"
@matthampton-stock2shop This is a PageHeader component styling issue that is not related to this PR. Can you provide some more info around how you produced this? See my attached screenshots for how it is rendering for me.

![Screenshot 2023-08-14 093958](https://github.com/stock2shop/console_v2/assets/129734011/d3e973a8-49fc-4425-8919-5655365fd3c1)


![Screenshot 2023-08-14 094014](https://github.com/stock2shop/console_v2/assets/129734011/bc7d3fac-6e80-4203-8ed0-1153851536fb)

2023-08-14 08:01 UTC, matthampton-stock2shop commented on src/components/Icons/IconUnlock.svelte
> +    clip-rule="evenodd"
Logged new issue

2023-08-14 08:44 UTC, justinengle-krs approved these changes

2023-08-14 09:19 UTC, matthampton-stock2shop commented on src/components/Icons/IconUnlock.svelte
> +<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
#208

2023-08-14 09:43 UTC, matthampton-stock2shop approved these changes

2023-08-14 09:44 UTC, merged