#224 + #208 - Product Template issues
stock2shop/console_v2 pull request #225
Opened 2023-08-16 13:49 UTC by justinengle-krs

fix loading state
fix some column spacing
fix attribute count

2023-08-21 08:22 UTC, casperlotter commented
@justinengle-krs I updated this PR.

![Screenshot 2023-08-21 102201](https://github.com/stock2shop/console_v2/assets/129734011/385eb891-ce52-43ff-87ef-aa1d36c5c333)

2023-08-22 10:19 UTC, justinengle-krs commented on src/models/products/product-attribute.ts
> +  toggle: { label: 'Yes / No', value: 'yes / no' },
so this means that it will save as yes/no to the db? Where the old console saves this as 'boolean'. I see thats catered for in the constructor above. But why the change?

2023-08-22 10:38 UTC, tauriqdolleyKRS requested changes
Left some comments. 

Saw comments related to dropdown defaulting. That seems to be working as per those comms.

2023-08-22 10:38 UTC, tauriqdolleyKRS commented on src/components/Settings/ProductTemplate.svelte
> +        ? results.filter((p) => p.error)[0].error
Can we guarantee there'll be an zero index error here? Quite a comprehensive set of ternary's..

2023-08-22 10:38 UTC, tauriqdolleyKRS commented on src/components/Settings/ProductTemplates.svelte
![image](https://github.com/stock2shop/console_v2/assets/142212593/6ad0f6ee-1bd4-49b4-bd6e-9de7e5b7478d)

Overflow scroll issue still seems to be present. Attribute count working correctly.

2023-08-23 07:30 UTC, casperlotter commented on src/models/products/product-attribute.ts
> +  toggle: { label: 'Yes / No', value: 'yes / no' },
@justinengle-krs @matthampton-stock2shop I updated it to set the value to boolean instead.

2023-08-24 10:19 UTC, tauriqdolleyKRS approved these changes

2023-08-30 06:55 UTC, mannyqi commented
Looks like the deletion of the template is missing a confirm.

2023-08-30 07:10 UTC, mannyqi requested changes

2023-08-30 07:10 UTC, mannyqi commented on src/components/Settings/ProductTemplates.svelte
>                await deleteProductTemplate(row.name);
Looks like the deletion of the template is missing a confirm. i.e. `confirm('Are you sure you want to delete this template?')`

2023-08-31 10:19 UTC, casperlotter commented on src/components/Settings/ProductTemplates.svelte
>                await deleteProductTemplate(row.name);
@mannyqi  This is called in the deleteProductTemplate function now

2023-09-04 10:54 UTC, mannyqi commented
@justinengle-krs when I click the "New Template" button, the modal just pops up with the loader and it just stays that way. There are no errors in the console either. Can you check if the same happens your side?

2023-09-05 15:35 UTC, TomRadford requested changes

2023-09-05 15:35 UTC, TomRadford commented on src/components/Settings/ProductTemplate.svelte
> +  $: isLoading = (!!productTemplateToEdit && ($templateDetails.isLoading || $templateDetails.isFetching)) || loading;
isLoading (which is just a shorthand for status === 'loading') indicates that "you have no data yet" in Query v4
(https://tkdodo.eu/blog/status-checks-in-react-query) 
Thus, if disabled, isLoading will be true. 

Knowing this, I believe simplifying this to
` $: isLoading = (!!productTemplateToEdit && $templateDetails.isLoading) || loading;`
will do the trick 🎉

2023-09-05 15:35 UTC, TomRadford commented on src/components/Settings/ProductTemplates.svelte
> +  $: productTemplateItems = createQuery(['meta_template-get'], () => productTemplateRepo.getAll());
not sure if this one needs to be reactive since it doesn't have any dependencies. (ie: it's just got the queryFn)

2023-09-05 15:35 UTC, TomRadford commented on src/components/Settings/ProductTemplate.svelte
> +    enabled: !!productTemplateToEdit && !templateItemsVC,
You can probably revert to `enabled: !!productTemplateToEdit ` if you go with my suggestion below 👌

2023-09-06 07:43 UTC, mannyqi commented
@justinengle-krs let me know when I can review again

2023-09-06 09:42 UTC, justinengle-krs commented
@mannyqi @TomRadford Please review and test

2023-09-15 11:06 UTC, mannyqi approved these changes

2023-09-15 11:06 UTC, mannyqi approved these changes

2023-09-15 11:16 UTC, TomRadford commented on src/components/Modal/CenterModal.svelte
> +      <div class="flex items-center px-6 py-4 border-b border-neutral-200 bg-white sticky top-0 z-10">
@justinengle-krs nit: was curious why we have both this component, as right Modal and then a generic `Modal` component that supports center, left and right alignment. I'd like to refactor all of these into `Modal` at some point but just want to double-check check there isn't another reason?

2023-09-15 11:17 UTC, TomRadford approved these changes
Looks good, just left a comment RE: modals :)

2023-09-15 11:19 UTC, justinengle-krs commented on src/components/Modal/CenterModal.svelte
> +      <div class="flex items-center px-6 py-4 border-b border-neutral-200 bg-white sticky top-0 z-10">
@TomRadford There was no important reason. That original modal was done by the previous devs - when I started on here, I think it was just easier to create that side modal from scratch to meet my needs at the time, and then subsequently someone else made the center one.
So I think no harm in refactoring them into 1 :)

2023-09-15 11:33 UTC, merged