#219 Subject Header & Customer Invites Endpoint
stock2shop/console_v2 pull request #258
Opened 2023-08-28 08:04 UTC by tauriqdolleyKRS

- Adds Subject Header Input Field on Customer Invite Modal
- Auto Populates Email Message if "custom_user_invite_message_markdown_template" channel meta key is present
- Hooked up sending of invites to API via api/users/invite POST
- Basic Styling (still require Figma access)

2023-08-28 14:01 UTC, casperlotter approved these changes

2023-08-30 07:33 UTC, matthampton-stock2shop commented
@tauriqdolleyKRS Could you add some screenshots for this?

And also, did you add any storybook screens for it? I think that would be good, if not...

2023-08-31 13:27 UTC, TomRadford commented on src/components/Customer/Details/SendInviteModal.svelte
> +  const channelMetaResult = useQuery(['channelMeta', channelId], () => channelsRepo.getChannelMeta(channelId), { enabled: !!channelId });
this can be declared reactively with the `$` label as per docs: https://tanstack.com/query/latest/docs/svelte/reactivity

2023-08-31 13:28 UTC, TomRadford commented on src/components/Customer/Details/SendInviteModal.svelte
> +  $: channelMetaResult.setOptions(['channelMeta', channelId], () => channelsRepo.getChannelMeta(channelId), { enabled: !!channelId });
this can be removed as per my comment below

2023-09-04 08:02 UTC, TomRadford requested changes
as per my comments

2023-09-07 12:15 UTC, TomRadford approved these changes

2023-09-07 12:16 UTC, merged