#212 & #211: Segments - Show Data Source & update/delete functionality
stock2shop/console_v2 pull request #262
Opened 2023-08-29 12:44 UTC by TomRadford

Resolves: #212 #211 
Design:
<img width="1005" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/f2b6d92e-c0d9-413e-a768-acde4f50d1fd">

Implementation:
<img width="1129" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/73739e32-5e26-4eba-b936-b05621cc6c27">

Segment table features:
- data source display
- 'add' functionality
- 'delete' functionality

Additional changes in this PR:
- add segment row header and delete
- add VS Code tailwind intellisense for cn util
- add additonal cn doc
- use existing data instead of invalidating state

2023-08-29 12:47 UTC, TomRadford commented on src/components/Segments/SegmentsList.svelte
> +    mutateSegmentModel = edit ? segment : new SystemSegment({ user_id: userId, owner: 'system', type: 'products' });
Allows us to share this this model for both update and delete operations,

2023-08-29 12:48 UTC, TomRadford commented on src/components/Segments/SegmentsList.svelte
> +    const segmentsPut = [...segments.filter((s) => s.type === mutateSegmentModel.type), mutateSegmentModel];
ensure quality check is strict ie: `===`

2023-08-29 12:50 UTC, TomRadford commented on src/components/Segments/SegmentsList.svelte
> +        [...segments.filter((s) => s.type !== mutateSegmentModel.type), ...(result.result as SystemSegment[])]
Added this here instead of invalidating the query as a means of saving on an additional `get` (during invalidation) since all the data we need already exists and we simply need to mutate the state accordingly.

2023-08-29 12:55 UTC, TomRadford commented on src/components/Segments/SegmentsList.svelte
> +      queryClient.setQueryData(['segments-get', userId], segments);
Added this here instead of invalidating the query as a means of saving on an additional get (during invalidation) since the mutated segments array will already exist as a result of the mutation of `segments` as per `bind:segment={mutateSegmentModel}` (mutateSegmentModel is a ref to segment when editing) in `AddSegmentModal`

2023-08-29 12:58 UTC, TomRadford commented on src/components/Segments/SegmentsList.svelte
> +      <SegmentsType type="customers" on:click={() => openModal('customers')} {segments} {segmentsRepo} {userId} {openEditModal} />
Instead of prop drilling, we could also make use of the [context api](https://learn.svelte.dev/tutorial/context-api), however, this implementation favours simplicity and, thus verbosity, over complexity.

2023-08-29 12:58 UTC, TomRadford commented on src/components/input/Dropdown.svelte
> +<div class={cn(`flex relative`, sideLabel ? 'flex-row items-center justify-between' : 'flex-col', className)}>
refactoring to use our new `cn` util

2023-08-29 13:00 UTC, TomRadford commented on src/repos/segments-repo.ts
> +        result: res.system_segments,
since we're getting data returned from this endpoint, I thought it would be valuable to return it here in order to mutate state (as noted above where I've used this changed to get rid of the query invalidation)

2023-08-31 10:01 UTC, casperlotter commented on src/components/Segments/SegmentsList.svelte
> +        [...segments.filter((s) => s.type !== mutateSegmentModel.type), ...(result.result as SystemSegment[])]
@TomRadford @matthampton-stock2shop @justinengle-krs 

My thoughts on this:

The GET request might ensure the API call for this resource is cached on the server.
The additional complexity introduced here in the code. For example, if similar code is run in the context of a ObjectVersionControl it might cause unintended side effects. So I would be careful to not make this a pattern we apply in general.

2023-08-31 10:25 UTC, TomRadford commented on src/components/Segments/SegmentsList.svelte
> +        [...segments.filter((s) => s.type !== mutateSegmentModel.type), ...(result.result as SystemSegment[])]
Thanks, Casper, @matthampton-stock2shop, I'm keen to get your opinion on this.
We could possibly invalidate all queries when ObjectVersionControl changes by means of changes to the `queryClient` config.

2023-09-11 08:15 UTC, mannyqi commented
@TomRadford 

I picked up a small bug where the name of the customer becomes undefined:
<img width="1190" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/69b30d7a-b119-4417-a591-7c4ce4240b81">


**Steps to reproduce:**
1. Add a segment
2. Click/move away from the page by clicking on another screen or browser tab
3. Click back on the segment page

Note that the customer name changes to "undefined undefined" after the content refreshes.

**Also, a couple of questions:**
1. Should the deletion of segments not have a confirmation?
2. Is the "chevron-down" icon needed for the data source? From the looks of it, we can no longer change the data source manually?
<img width="1172" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/dbabece6-29d6-4683-8df8-8f61948ac010">

2023-09-13 08:11 UTC, TomRadford commented
> @TomRadford
> 
> I picked up a small bug where the name of the customer becomes undefined: <img alt="image" width="1190" src="https://user-images.githubusercontent.com/2038721/266951768-69b30d7a-b119-4417-a591-7c4ce4240b81.png">
> 
> **Steps to reproduce:**
> 
> 1. Add a segment
> 2. Click/move away from the page by clicking on another screen or browser tab
> 3. Click back on the segment page
> 
> Note that the customer name changes to "undefined undefined" after the content refreshes.
> 
> **Also, a couple of questions:**
> 
> 1. Should the deletion of segments not have a confirmation?
> 2. Is the "chevron-down" icon needed for the data source? From the looks of it, we can no longer change the data source manually?
> 
> <img alt="image" width="1172" src="https://user-images.githubusercontent.com/2038721/266953681-dbabece6-29d6-4683-8df8-8f61948ac010.png">

@mannyqi should be resolved now.  That undefined issue was resolved by syncing with master which included some useful query improvements.

2023-09-15 10:42 UTC, mannyqi requested changes
Other than this one small fix, everything else seems to be working.

2023-09-15 10:42 UTC, mannyqi commented on src/stories/components/80-Segments/10-SegmentRow.stories.svelte
> +  import { QueryClient, QueryClientProvider } from '@sveltestack/svelte-query';
Storybook build failed due to svelte-query not being found.

![image](https://github.com/stock2shop/console_v2/assets/2038721/5726c33a-b817-41b1-883e-616e1564abc9)

2023-09-19 07:21 UTC, mannyqi approved these changes

2023-09-19 07:24 UTC, merged

2023-09-22 12:12 UTC, matthampton-stock2shop commented on src/components/form/Btn.svelte
> +  export let size: Size = 'medium';
I'm not 100% sure why, but it seems like maybe these changes have affected how the buttons font looks (it's become big)... Could obviously be somewhere else, too... not sure:

![image](https://github.com/stock2shop/console_v2/assets/124143173/b5142b5f-849a-4323-aac3-5e1bf1e8c293)

2023-09-22 12:15 UTC, TomRadford commented on src/components/form/Btn.svelte
> +  export let size: Size = 'medium';
100% this PR broke button sizing