#254 Product 'mode' on product listing view
stock2shop/console_v2 pull request #270
Opened 2023-09-01 09:27 UTC by TomRadford

2023-09-01 09:45 UTC, TomRadford commented on src/components/Configurators/ColumnConfigurator/ColumnConfiguratorModal.svelte
> +  {#if showColumnConfigurator}
this fixed polluting the dom with this component (ie with `hidden` class) when it's not being displayed

2023-09-01 09:46 UTC, TomRadford commented on src/components/Modal.svelte
> +{#if open}
changes here clean up our generic modal implementation

2023-09-01 09:47 UTC, TomRadford commented on src/components/Modal.svelte
> +        y: position === 'center' ? -100 : undefined,
sets animation direction based on modal position type

2023-09-01 09:49 UTC, TomRadford commented on src/components/grids/FacetsManager.svelte
> -  const onWindowClick = (e: MouseEvent) => {
this does the same as our new `clickOutside` actions

2023-09-01 10:01 UTC, TomRadford commented on src/routes/Products.svelte
> +  export const showProducts = writable(false);
here we're using the module context to declare a writeable store from this parent component to prevent drilling. We could totally declare this store in the utils folder but I thought it would perhaps be better suited here since this piece of state is tied directly to this component.

Instead of prop drilling through to the required components, we can simply import this store and use it where needed to filter facets.

2023-09-01 10:02 UTC, TomRadford commented on src/stories/components/10-form/12-Toggle.stories.svelte
> +<Meta title="components/form/Toggle" component={Toggle} />
this toggle but need a story still 📚

2023-09-01 10:04 UTC, TomRadford commented on src/styles/custom/toggle.css
> +  content: '';
prettier rules seem to want to clean up CSS files since this one hasn't been touched in a while.

2023-09-01 10:04 UTC, TomRadford commented on src/styles/custom/toggle.css
> +  @apply bg-brand-notification;
the toggle wasn't using our official blue colour.

2023-09-05 06:37 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +      const prices = value.variants.map((v) => v.price as number);
I think we can remove this code now that we are doing it the simple way,right?

2023-09-05 06:37 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +    removeAllFilters();
Let's talk to Chris about this - I feel like keeping the product level filters makes sense

2023-09-05 06:37 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +      facetsArray={$facetsArray.filter((facet) => ($showProducts ? facet.key.split('.')[0] !== 'variants' : facet))}
I'm feeling like extracting a function to do this filter might be a good idea - cos we might need to get smarter about it later on (e.g. price tiers are variant fields, but may not start with 'variants.')

2023-09-05 14:03 UTC, TomRadford commented on src/routes/Products.svelte
> +    return () => ($showProducts = false);
Resets when this parent component is unmounted

2023-09-05 14:04 UTC, TomRadford commented on src/routes/Products.svelte
> +          setNumberRangeFilter(facet.key);
Reverted back to only resetting prices as per @matthampton-stock2shop's feedback

2023-09-07 13:55 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +          setNumberRangeFilter(facet.key);
```
const removeFilters = (filter) => {
    update((entry) => {
      Object.values(entry.facets).filter(f => filter ? filter(f): true).forEach((facet) => {
        if (isDefaultFacet(facet)) {
          facet.buckets_filters = [];
        }
        if (isNumberRangeFacet(facet)) {
          delete facet.range;
        }
        if (isDateRangeFacet(facet)) {
          delete facet.range;
        }
      });
    });
    setFrom(0);
  };
```
We thought...

2023-09-07 13:56 UTC, matthampton-stock2shop requested changes
The filter changing change

2023-09-08 06:54 UTC, matthampton-stock2shop requested changes
Something still a bit funny on toggle

2023-09-08 06:54 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +    if (!$showProducts) return;
There is something still not quite right here in that when switching to product mode, it does seem to clear the filter on price - but then doesn't re-run the queries (or at least something doesn't refresh).

See here:

https://github.com/stock2shop/console_v2/assets/124143173/c2a974d3-5554-45bb-81b4-b9f765fb8313

2023-09-08 07:09 UTC, TomRadford commented on src/routes/Products.svelte
> +    if (!$showProducts) return;
Should be resolved :) 

https://github.com/stock2shop/console_v2/assets/7515754/67303208-e678-4eec-b017-aabbce7c9671

2023-09-08 07:16 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +    if (!$showProducts) return;
Not quite, I'm afraid ... i.e. it does clear it from the filter config - but doesn't re-run the queries (i.e. there are too few items in the resultset when you switch to products if you put on a restrictive price filter)

2023-09-08 07:17 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +    if (!$showProducts) return;
(e.g. put max price R45 and then switch to product to see what I'm talking about)

2023-09-08 07:17 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +    if (!$showProducts) return;
Oh! and 'toys and games' at the same time!

2023-09-08 07:18 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +    if (!$showProducts) return;
(there should be two items only matching that combo)

2023-09-08 07:18 UTC, matthampton-stock2shop commented on src/routes/Products.svelte
> +    if (!$showProducts) return;
(well 2 products - with 4 variants total)

2023-09-08 08:24 UTC, merged