#214: Status has a background colour & add other connectors
stock2shop/console_v2 pull request #272
Opened 2023-09-05 08:59 UTC by TomRadford

Design:
<img width="1006" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/3b063181-10ba-4adb-aa86-17d2b9f37f0d">
Implementation:
<img width="1195" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/06628d0a-b5da-46b5-84e5-0fb3115e13ac">

2023-09-05 09:01 UTC, TomRadford commented on src/components/Status.svelte
> -  export let level:Levels = Levels.WARNING;
removal of enums in favour of a literal union is just a personal choice to clean up this implementation a bit.

2023-09-05 09:03 UTC, TomRadford commented on src/components/Connectors/Connectors.svelte
> +      items={$sourcesData.data.map((source) => ({ id: source.id.toString(), name: source.description, linked: !!source.active }))}
not sure if `active` is the right property to indicate if something is `linked`?

2023-09-07 14:09 UTC, matthampton-stock2shop requested changes

2023-09-07 14:09 UTC, matthampton-stock2shop commented on src/components/Connectors/Connectors.svelte
> +      items={$sourcesData.data.map((source) => ({ id: source.id.toString(), name: source.description, linked: !!source.active }))}
I think so

2023-09-07 14:09 UTC, matthampton-stock2shop commented on src/components/Connectors/Connectors.svelte
> +    <Connector
Could we call this ConnectorGroup?

2023-09-08 06:56 UTC, matthampton-stock2shop approved these changes

2023-09-08 06:56 UTC, merged