#244: `Save changes` state disabled state fixed
stock2shop/console_v2 pull request #276
Opened 2023-09-07 14:24 UTC by TomRadford

2023-09-07 14:37 UTC, TomRadford commented on src/components/Connectors/ConfigItems/ProductFilters.svelte
> +  $: isLoading = loading || $availableFieldsData.isLoading || $rulesData.isLoading;
isFetching is not needed here as it causes loader flash when stale query data is being revalidated

2023-09-07 14:39 UTC, TomRadford commented on src/models/version-controlled.ts
> + * const serverData = new ObjectVersionControl<ServerData>(initialData)
popped this here so that I remember this is a custom store implementation and should be subscribed to 😝

2023-09-07 14:42 UTC, TomRadford commented on src/components/Connectors/ChannelMaster.svelte
> +        <!-- TODO: Remove -->
As per https://github.com/stock2shop/console_v2/commit/f31e21231b0c522880586afbc65d90dc0edb0994#r126696527 I want to clean this up when there's time

2023-09-08 07:05 UTC, matthampton-stock2shop requested changes

2023-09-08 07:05 UTC, matthampton-stock2shop commented on src/models/version-controlled.ts
> +      this.workingCopy = JSON.parse(this.stringify(newServerVersionJson)) as T;
This looks wrong to me - that it is stringifying the newServerVersionJson - it should just be parsing it...

I'm not sure how this has been working TBH cos it is going to result in having string instead of an object for the working copy.. Or am I mistaken? 

Maybe no-one has seen the issue because it requires you to make a change on the server while the console is open to hit this part of the code.

i.e. open the console in two tabs to the same screen

And make a change on one, then go to the other and see it break

Would you mind checking for me?

2023-09-08 07:10 UTC, matthampton-stock2shop commented on src/components/Connectors/ChannelMaster.svelte
> +    changesMade = channelMetaValuesArray.some((c) => c.changesMade) || prodFiltersChangesMade || prodFiltersChangesMade;
I've also still got a bit of funny behaviour with the save changes button (sorry):

https://github.com/stock2shop/console_v2/assets/124143173/aadd6877-8f27-4418-8a3e-98ba4711c7e2

2023-09-08 07:21 UTC, TomRadford commented on src/models/version-controlled.ts
> +      this.workingCopy = JSON.parse(this.stringify(newServerVersionJson)) as T;
Can confirm, this should have been `this.workingCopy = JSON.parse(newServerVersionJson) as T;`

2023-09-08 07:56 UTC, TomRadford commented on src/models/version-controlled.ts
> +      this.workingCopy = JSON.parse(this.stringify(newServerVersionJson)) as T;
Seems that after checking this seem to be getting state on channelMetaValuesArray behaviour that isn't reactive instantly reactive.
https://github.com/stock2shop/console_v2/assets/7515754/257ac4ef-412f-4bed-b503-ca15a8ae0422

@matthampton-stock2shop perhaps I should try action that refactor today (into a single VersionControlled store) to reduce complexity and allow for (hopefully) more predictive reactive behaviour.

2023-09-08 08:37 UTC, TomRadford commented
Chatted with Matt and we're planning to tackle a refactor on Monday using a singular VersionControlled store as per https://github.com/stock2shop/console_v2/pull/276#discussion_r1319507812

2023-09-08 10:46 UTC, matthampton-stock2shop commented on src/components/Connectors/ChannelMaster.svelte
> +    changesMade = channelMetaValuesArray.some((c) => c.changesMade) || prodFiltersChangesMade || prodFiltersChangesMade;
We're going to sort this out separately

2023-09-08 10:46 UTC, matthampton-stock2shop approved these changes

2023-09-08 10:48 UTC, merged