304
stock2shop/console_v2 pull request #307
Opened 2023-11-01 08:47 UTC by TomRadford

2023-11-02 09:39 UTC, TomRadford commented on src/components/Product/Attribute.svelte
> +  $: attributeIndex = $product.workingCopy.meta.findIndex((att) => att.key === attribute.meta?.key);
@matthampton-stock2shop looks like your IDE isnt looking at our prettier config sadly

2023-11-02 09:47 UTC, TomRadford commented on src/models/version-controlled.ts
> +      console.info('Changed key', { keyPath, left, right });
@matthampton-stock2shop seems like WebStorm doesnt seem to be formatting on our prettier config

2023-11-02 10:09 UTC, matthampton-stock2shop commented on src/models/version-controlled.ts
> +      console.info('Changed key', { keyPath, left, right });
Ah ... Maybe I need to ask it to autoformat - I haven't been in the habit of using that feature

2023-11-03 09:12 UTC, TomRadford commented
@matthampton-stock2shop rendering of input if blank value should be resolved now

2023-11-06 09:54 UTC, Ayano2000 requested changes
I have tested basic `CRUD` for `productmeta`, adding and removing meta via templates (removing all meta items for a template does deselect the template).

- If a template is removed, any meta that it may have added to a product stays

- [ ]  Default `metatemplate` values do not show when adding a template

-------------

I believe this is not a part of this PR but:
- I cannot edit any of the existing meta_templates, `Successfully added new however some attribute(s) had an error. Error: Undefined property: stdClass::$name`
- Sometimes the modal for creating/editing meta templates gets cached.
- When adding a `metatemplate` of type dropdown, we cannot add any selectable values. 

@TomRadford I'm not sure all of these issues are related to this PR, but I think showing a templates default values when adding it should be working before we merge this

2023-11-14 07:14 UTC, Ayano2000 approved these changes
LGTM

2023-11-14 08:29 UTC, merged