#209 Edit customer addreses
stock2shop/console_v2 pull request #314
Opened 2023-11-02 17:02 UTC by TomRadford

2023-11-10 06:43 UTC, mannyqi requested changes
I also just noticed that the AddressList storybook is broken:

<img width="1728" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/aeab0912-fbd2-4dcc-a848-236c6fcc7cbe">

Looks like [type](https://github.com/stock2shop/console_v2/blob/1727d7c30623ea2bcbe0b512ec02bad393232556/src/components/Customer/Details/AddressList.svelte#L22) is undefined somehow.

2023-11-10 06:43 UTC, mannyqi commented on src/components/Customer/Details/Addresses.svelte
> +  const saveAction = () => {
There's a weird little bug where the default address is set to false after clicking the "Edit Address" on the side modal even though it is true.

To reproduce bug:
1. Create existing customer address with "Default Address" set to active
2. Edit the customer and then the default address (note the default address toggle is set to true at this point)
3. Click "Edit Address" and notice the default address tag is now missing
<img width="292" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/342d9ca6-244d-4d7c-acb7-7ef7125acc75">

I tried to debug it myself but couldn't figure out where the default address was getting lost...

2023-11-10 12:22 UTC, TomRadford commented on src/components/Customer/Details/Addresses.svelte
> +  const saveAction = () => {
@mannyqi would you mind giving this another try now. 
You should only be able to set one default and the default shouldn't unset itself on edit. 
Made some silly mistakes including not using a deep copy for the addressToEdit state variable - thus resulting in some strange behaviours - hopefully should be working okay now

Only one strange issue regarding the company name. Will document below

2023-11-10 13:13 UTC, TomRadford commented on src/components/Customer/Details/Addresses.svelte
> +  const saveAction = () => {
@mannyqi  I noticed that when you set the first billing address, it will set that as the `companyName` on the customer - just confirming this is an intentional side effect?

2023-11-14 12:47 UTC, mannyqi commented
@TomRadford sorry, would you mind resolve the conflicts in this branch please? I'd like to get this one out the way for you. Sorry about delay

2023-11-14 15:08 UTC, TomRadford commented
@mannyqi  resolved conflicts 👍

2023-11-15 06:43 UTC, mannyqi commented
@TomRadford All is working great. Just picked up a small style issue:

<img width="763" alt="image" src="https://github.com/stock2shop/console_v2/assets/2038721/dccf9ff6-afbb-49de-9579-420d887a9a32">

Maybe this can be fixed in another PR so we can get this one merged so long? If yes, then I'll approve this PR.

2023-11-15 08:18 UTC, mannyqi approved these changes

2023-11-15 08:22 UTC, merged