Chris/feature/dashboard
stock2shop/console_v2 pull request #368
Opened 2023-12-11 10:31 UTC by flumonion

2023-12-14 11:17 UTC, TomRadford commented
flagging if this hover-over menu should do anything:
![image](https://github.com/stock2shop/console_v2/assets/7515754/c2332075-3e1c-4fcd-a2b2-b56a94294a70)

Can resolve if it doesn't have to do with this PR

2023-12-14 11:27 UTC, TomRadford commented
Something that doesn't make sense to me from a UI perspective is these two dropdowns (the one is open with four options):
![image](https://github.com/stock2shop/console_v2/assets/7515754/58f93f8f-c187-4853-838c-f889f3a5d386)

Changing one of them changes the other which causes the whole UI to revert to Skeleton. 
I believe that this dropdown could be placed above or somewhere where it isn't replicated ie:
![image](https://github.com/stock2shop/console_v2/assets/7515754/8f88a2ec-6204-488a-88e1-ff5d1f00ec3d)

In Dashboard.svelte this could be:
```
  <div class="mt-7">
    <div class="mb-2 mt-10 flex w-full justify-center self-center">
      <Dropdown
        options={getGraphEntities()}
        bind:value={entity}
        className="w-24 mr-[27px] "
        inputClass="font-bold text-small text-neutral-700 px-3 py-0 border-neutral-200 h-[24px] rounded-[5px]"
      />
    </div>
    <div class="grid gap-6 lg:grid-cols-1 xl:grid-cols-2">
      <DashboardInfoError bind:entity logs={logsIngress} direction="ingress" {isLoading} {config} />
      <DashboardInfoError bind:entity logs={logsEgress} direction="egress" {isLoading} {config} />
    </div>
  </div>
```

2024-01-03 11:04 UTC, flumonion commented on package.json
> +    "cron-parser": "^4.9.0",
it is being used `DashboardSyncPull`

2024-01-03 11:05 UTC, flumonion commented on s2s.dic
i use it to remove errors in my ide, if that does not bother you, you can leave it.

2024-01-03 11:05 UTC, flumonion commented on src/components/Dashboard/DashboardSync.svelte
> +        <Skeleton class="h-8 w-36" shimmer={true} />
can you give an example of the shift?

2024-01-03 11:06 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +    <DashboardHeader {isLoading} bind:range />
removed.

2024-01-03 11:07 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +  $: queryConfig = createConfigQuery();
https://github.com/stock2shop/console_v2/pull/368/commits/a697f88690d67428aac940615a4d4534d0a244b4

2024-01-03 11:07 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +  $: queryLogsSourceSync = createLogsSourceSyncQuery();
https://github.com/stock2shop/console_v2/pull/368/commits/a697f88690d67428aac940615a4d4534d0a244b4

2024-01-03 11:07 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +  $: tradeChannel = $queryConfig.data && hasTradeChannel($queryConfig.data);
https://github.com/stock2shop/console_v2/pull/368/commits/a697f88690d67428aac940615a4d4534d0a244b4

2024-01-03 11:07 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +  $: fulfillmentService = $queryConfig.data && hasFulfillmentService($queryConfig.data);
https://github.com/stock2shop/console_v2/pull/368/commits/a697f88690d67428aac940615a4d4534d0a244b4

2024-01-03 11:07 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +    logsIngress = $queryLogsIngress.data;
https://github.com/stock2shop/console_v2/pull/368/commits/a697f88690d67428aac940615a4d4534d0a244b4

2024-01-03 11:07 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +    logsEgress = $queryLogsEgress.data;
https://github.com/stock2shop/console_v2/pull/368/commits/a697f88690d67428aac940615a4d4534d0a244b4

2024-01-03 11:07 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +    sourceSync = $queryLogsSourceSync.data;
https://github.com/stock2shop/console_v2/pull/368/commits/a697f88690d67428aac940615a4d4534d0a244b4

2024-01-03 11:07 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +      source = getSource(config);
https://github.com/stock2shop/console_v2/pull/368/commits/a697f88690d67428aac940615a4d4534d0a244b4

2024-01-03 11:10 UTC, flumonion commented on src/components/Dashboard/Dashboard.svelte
> +  let config: Config;
https://github.com/stock2shop/console_v2/pull/368/commits/7a8eb3d05a41664032e16358fa7efd489103a615

2024-01-03 11:11 UTC, flumonion commented on src/components/Dashboard/DashboardInfoBlock.svelte
> +    let info = logsIngress.aggregations?.range?.buckets?.info?.entities?.buckets;
https://github.com/stock2shop/console_v2/pull/368/commits/c14c0476e2feae92be228111296fe90d0037ec66

2024-01-03 11:14 UTC, flumonion commented on src/components/Dashboard/DashboardInfoError.svelte
> +      <Btn on:click={goToLogs} class="mt-6" size="small" variant="gray-outline">View Logs</Btn>
I did not want to have to reinvent the design of the button, is that not a good trade off?

2024-01-03 11:15 UTC, flumonion commented on src/components/Dashboard/DashboardInfoError.svelte
> +  import IngressChart from '@/components/Dashboard/DashboardInfoErrorChart.svelte';
https://github.com/stock2shop/console_v2/pull/368/commits/35574cd3d72ec4e53f7f00470b55b67e81003795

2024-01-03 11:17 UTC, flumonion commented on src/components/Dashboard/DashboardInfoErrorChart.svelte
> +    let info = esData.aggregations?.range?.buckets?.info?.entities?.buckets;
https://github.com/stock2shop/console_v2/pull/368/commits/2a22408bbf25fa473578f965befd99b0da2938c6

2024-01-03 11:18 UTC, flumonion commented on src/components/Dashboard/DashboardInfoErrorList.svelte
not following this comment, can you link to the code?

2024-01-03 11:19 UTC, flumonion commented on src/components/Dashboard/DashboardHeader.svelte
> +  import DashboardTimeFrameFilter from './DashboardRangeSelector.svelte';
https://github.com/stock2shop/console_v2/pull/368/commits/8e623e7672c2d8771ebcacfc55c435c4aa4327eb

2024-01-03 11:20 UTC, flumonion commented on src/components/Dashboard/DashboardRangeSelector.svelte
> +      on:click={() => (range = key)}
https://github.com/stock2shop/console_v2/pull/368/commits/3431466597509f85696cb47767e828b77648e9a8

2024-01-03 11:21 UTC, flumonion commented on src/components/Dashboard/DashboardSync.svelte
> +{#if sources.length > 0}
yes, very low...
You cannot use the system without a source.

2024-01-03 11:22 UTC, flumonion commented on src/components/Dashboard/DashboardSyncPull.svelte
> +    on:click={goToLogs}
but then we need to restyle the href?

2024-01-03 11:22 UTC, flumonion commented on src/components/Dashboard/DashboardSyncPush.svelte
see response

2024-01-03 11:23 UTC, flumonion commented on src/lib/date-utils.ts
> +  const short = new Intl.DateTimeFormat('en', {
bug fix here.

2024-01-03 11:24 UTC, flumonion commented on src/models/config/config.ts
> + * @param config
my ide added this one in, have removed it.
https://github.com/stock2shop/console_v2/pull/368/commits/04b55c1c4d9b6c3a9687fd78cc478d22dc83b766

2024-01-03 11:46 UTC, TomRadford commented on src/components/Dashboard/DashboardSync.svelte
> +        <Skeleton class="h-8 w-36" shimmer={true} />
It was when we do not know the sources count for:
<img width="682" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/aac51985-f8fe-45c3-ad2a-59e277001da3">
so we cant determine the height of the skeleton

2024-01-04 09:35 UTC, TomRadford requested changes

2024-01-04 09:35 UTC, TomRadford commented on src/stories/test-data/repos/logs-repo.ts
> +    return undefined as unknown as InfoErrorResponse;
@flumonion starting point to return mock data

2024-01-04 09:35 UTC, TomRadford commented on src/components/Dashboard/DashboardInfoError.svelte
> +      <Btn on:click={goToLogs} class="mt-6" size="small" variant="gray-outline">View Logs</Btn>
you don't need to :) - just do:
```
<a href='/logs'>
<Btn class="mt-6" size="small" variant="gray-outline">View Logs</Btn>
</a>
```

2024-01-04 09:38 UTC, TomRadford commented on src/stories/test-data/repos/logs-repo.ts
> +    return undefined as unknown as InfoErrorResponse;
you can ignore this (just leave it for now) if you remove `src/stories/routes/98-Dashboard.stories.svelte`

2024-01-04 10:17 UTC, flumonion commented on src/components/Dashboard/DashboardSync.svelte
> +        <Skeleton class="h-8 w-36" shimmer={true} />
ja, so that may be a rare case... prepared to leave this for now?

2024-01-05 09:30 UTC, TomRadford approved these changes

2024-01-05 09:31 UTC, merged