Use combobox in appropriate places + field selector fixes and enhancements
stock2shop/console_v2 pull request #374
Opened 2023-12-14 10:36 UTC by TomRadford

Note: this also add some essential fixes to `ComboBox` and `FieldSelector`

2024-01-02 07:52 UTC, matthampton-stock2shop commented on src/components/Connectors/ConfigItems/Channel/ProductFilters.svelte
>    import Icon from '@/components/Icons/Icon.svelte';
(I didn't get very far on this - just the one very surface level comment - but Chris is going to have a look deeper now)

2024-01-02 08:02 UTC, TomRadford commented
@flumonion note the following for your review on this one:
The places in which I've used this new Combobox component in this PR are by no means exhaustive. 
Rather I wanted to get this one merged after tomr/tags-input since there are a few important fixes/enhancements I made.

Hence I've split off additional work into another new issue: https://github.com/stock2shop/console_v2/issues/375

2024-01-02 09:55 UTC, TomRadford commented
<img width="380" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/8c27df36-7c88-4afb-810d-78e50edf93c7">
 use combobox with values drop down

2024-01-02 10:38 UTC, flumonion requested changes

2024-01-02 10:38 UTC, flumonion commented on src/components/Connectors/ConfigItems/Channel/ProductFilters.svelte
>            placeholder="Select a field"
I think we should have a `FieldValueSelector` which uses the combo box.
Our field selector should swap out the dropdown when selecting a dynamic field.

![Screenshot 2024-01-02 at 12 37 36](https://github.com/stock2shop/console_v2/assets/1546805/22b4bd96-ddc5-4772-9db3-e5a919b621e9)

2024-01-03 12:45 UTC, TomRadford commented on src/components/Connectors/ConfigItems/Channel/ProductFilters.svelte
>            placeholder="Select a field"
@flumonion have a look at this FieldSelector that uses the new `DynamicFieldSelector` instead of `DynamicFieldModal` component when selecting Dynamic fields - feels much cleaner imo 

https://github.com/stock2shop/console_v2/assets/7515754/c3c8ec48-756e-434a-86a1-b8f077785636

2024-01-03 15:10 UTC, TomRadford commented on src/components/Connectors/ConfigItems/Channel/ProductFilters.svelte
>            placeholder="Select a field"
Additional feedback:
- remove the chevron 
- combobox clear if defocused - should depend on canAdd!
- combobox hit enter to create
- combobox 
- properly query field search endpoint with debounce -->

2024-01-04 08:53 UTC, TomRadford commented
not this PR also includes work from `tomr/tags-input` - we decided to consildate it into one PR

2024-01-04 16:32 UTC, TomRadford commented on src/components/Connectors/ConfigItems/Channel/ProductFilters.svelte
>            placeholder="Select a field"
The new behaviour of combobox when an existing/selected value is part of the list that's still loading in:

https://github.com/stock2shop/console_v2/assets/7515754/fb4f8084-917f-44ba-a8ad-b492b89ce2d9

It will list it as new until the options are loaded in and then remove the `new` option if the value already exists in the list.

2024-01-08 08:08 UTC, TomRadford commented
Example of the combination of FieldSelector and FieldValueSelector in action:

https://github.com/stock2shop/console_v2/assets/7515754/b3769a7d-3cf8-4669-bfd5-15182155e805

2024-01-09 07:48 UTC, flumonion requested changes

2024-01-09 07:48 UTC, flumonion commented on src/stories/components/10-form/FieldSelector/FieldValueSelector.stories.svelte
> +<script lang="ts">
The field selector has a compact dropdown.
The value selectors are expanded (40px per line).
<img width="1055" alt="Screenshot 2024-01-09 at 09 00 27" src="https://github.com/stock2shop/console_v2/assets/1546805/5cbfff83-8ddf-48b5-ab6e-2baafde44b4a">
 
<img width="1043" alt="Screenshot 2024-01-09 at 09 00 38" src="https://github.com/stock2shop/console_v2/assets/1546805/74a629c4-e659-4b1e-bc0d-a91b2227c502">

<img width="1047" alt="Screenshot 2024-01-09 at 09 00 13" src="https://github.com/stock2shop/console_v2/assets/1546805/552b57f5-6801-4d31-8d58-9305a5281ac2">

We don't have a design for dropdowns, the only reference i could find was this one

<img width="639" alt="Screenshot 2024-01-09 at 08 55 09" src="https://github.com/stock2shop/console_v2/assets/1546805/3d36beaf-74e4-4c8f-8f83-b79d218064cc">

Whatever the case, we need to figure a consistent one out and use that.
My feeling is the compact option you created works best.
Perhaps there is another dropdown example hiding somewhere in figma?

2024-01-09 07:48 UTC, flumonion commented on src/components/Connectors/ConfigItems/Channel/ProductFilters.svelte
> +  import { createFieldsQuery } from '@/queries/fields.query';
as nice as the little pill showing the 'custom fields' is (the one in the input box) i think it does cause spacing issues. I think we might need to scrap it. having the field name alone should be enough context?
Just an idea.. what do you think?

2024-01-09 07:48 UTC, flumonion commented on src/components/Segments/AddSegmentModal.svelte
> +  import { createFieldsQuery } from '@/queries/fields.query';
After saving segment with custom field get 'undefined' in the list

<img width="918" alt="Screenshot 2024-01-09 at 09 41 50" src="https://github.com/stock2shop/console_v2/assets/1546805/c51fff04-fa71-4019-b359-dab4b1820ddb">

2024-01-09 07:48 UTC, flumonion commented on src/components/Segments/AddSegmentModal.svelte
> +  import { createFieldsQuery } from '@/queries/fields.query';
I think this screen should be as per the design.
We should have a link called "Customer Segments" and another called "Product Segments" then it can look exactly as design.
Styling is out the screen, might be worth making a new issue for this one, leave off this pr?

2024-01-09 07:48 UTC, flumonion commented on src/components/input/OperatorSelector.svelte
> +  export let value: string;
howcome operator selector uses combo box?
Is it not just a simple dropdown?

2024-01-09 11:38 UTC, TomRadford commented on src/stories/components/10-form/FieldSelector/FieldValueSelector.stories.svelte
> +<script lang="ts">
Consolidated the Combobox dropdown and field selector dropdown styling to be consistent:

https://github.com/stock2shop/console_v2/assets/7515754/2ce40e3a-27dc-4465-b109-732ed7560e8d

2024-01-09 14:42 UTC, TomRadford commented on src/components/Segments/AddSegmentModal.svelte
> +  import { createFieldsQuery } from '@/queries/fields.query';
styling should be resolved - looks like design now

2024-01-12 10:35 UTC, TomRadford commented on svelte.config.js
> +  // using sequence breaks source maps - leaving this here in case we need it again for melt-ui
@matthampton-stock2shop fyi I found the culprit that was breaking our sourcemaps, leaving out 'svelte-sequential-preprocessor' seems to still work fine :) keeping these comments here for now incase we encounter any other funky issues

2024-01-18 05:12 UTC, flumonion commented
@TomRadford  I would like to merge this.
There is a conflict on package-lock.json, can you resolve so i can merge.

2024-01-18 12:12 UTC, flumonion commented on src/components/Controls/Select.svelte
> +  export let label = '';
Does select need a label?
Would that not happen outside of this component?

2024-01-18 12:17 UTC, flumonion commented on src/components/Controls/Select.svelte
> +  {#if label}
<img width="1005" alt="Screenshot 2024-01-18 at 14 14 08" src="https://github.com/stock2shop/console_v2/assets/1546805/963a5700-1070-4533-977d-1b9faa526cc9">

2024-01-18 12:19 UTC, flumonion commented on src/components/Controls/Select.svelte
> +      <div
<img width="732" alt="Screenshot 2024-01-18 at 14 19 11" src="https://github.com/stock2shop/console_v2/assets/1546805/1db5801e-6756-40e2-8386-091d769cbd5a">

2024-01-18 14:27 UTC, TomRadford commented on src/components/Controls/Select.svelte
> +  {#if label}
looks like this might be a WebStorm svelte/eslint issue, seems to be valid on my side since this was lifted directly from melt-ui's docs

2024-01-18 14:37 UTC, TomRadford commented on src/components/Controls/Select.svelte
> +      <div
woops, will resolve. Very interesting that this error/hint seems to come from WebStorm directly (ie: I spun up a stackblitz instance to make double double sure my lcoal VS Code instance isn't broken and it this feedback definitely seems to be a webstorm value-add - nice :) )

2024-01-18 14:45 UTC, TomRadford commented on src/components/Controls/Select.svelte
> +    if (JSON.stringify($selected?.value.value) !== JSON.stringify(value)) {
Yes, its when we want to change non-string state, ie in XeroTenant.svelte -` internalOption` is typed as `XeroTenantConnection`

2024-01-18 14:46 UTC, TomRadford commented on src/components/input/OperatorSelector.svelte
> +  export { className as class };
resolved

2024-01-18 15:29 UTC, flumonion commented on src/components/Controls/Select.svelte
> +  {#if label}
<img width="1059" alt="Screenshot 2024-01-18 at 17 28 40" src="https://github.com/stock2shop/console_v2/assets/1546805/78e10144-9502-4362-9e1b-b2e270ae64d5">

what happens if you run `npx eslint src/components/Controls/Select.svelte`?

2024-01-18 15:31 UTC, flumonion commented on src/components/Controls/Select.svelte
> +      <div
<img width="792" alt="Screenshot 2024-01-18 at 17 31 20" src="https://github.com/stock2shop/console_v2/assets/1546805/6bc5aee8-93ac-456d-b93c-4eae37702b88">

going to leave this one for now.

2024-01-19 05:26 UTC, merged