Add Product Attributes, Melt for Modal and PromptModal
stock2shop/console_v2 pull request #387
Opened 2024-01-15 14:02 UTC by TomRadford

2024-01-18 15:05 UTC, flumonion requested changes

2024-01-18 15:05 UTC, flumonion commented on src/components/Controls/FieldSelector/DynamicFieldSelector.svelte
> +  import { isValidContract } from '@/models/pricing-contracts/pricing-contract';
<img width="495" alt="Screenshot 2024-01-18 at 17 01 04" src="https://github.com/stock2shop/console_v2/assets/1546805/77518232-9568-4fd5-8a5a-e0ce9c70b580">

2024-01-19 08:36 UTC, TomRadford commented on src/components/Modal/USE_MODAL.md
> +- Use the `AddEditModal.svelte` wrapper component for Add/Edit style modals
AddEditModal was renamed to prompt modal

2024-01-19 11:30 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +  import Btn from '@/components/form/Btn.svelte';
This component is effectively a route that supports two different sets of params (ie: the entity) so that we can easily just pass in the correct entity and entity store to make the appropriate changes. 
<img width="727" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/2cf89058-013a-4e33-9617-2fddbb835bc7">

 
 Moving this logic into the +page.svelte for [entity]/attributes, would make the component slightly harder to use but I think I've found a happy middle that makes things a little less complex:

<img width="644" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/f87425a6-7ab9-47fc-a848-a6877cea4db6">

Moving save changes handler and templates up the tree (as props) would put a lot of external complexity in the +page.svelte/user of the Attribute component, so I think I'd like to keep those as is - unless we need to use this Attributes component in other places (which is effectively a page component as mentioned above).

Happy medium:
3085036123abf6c1469ad0a76dc4674631f47572

2024-01-19 11:55 UTC, TomRadford commented on src/components/Controls/FieldSelector/DynamicFieldSelector.svelte
> +  import { isValidContract } from '@/models/pricing-contracts/pricing-contract';
added a nice eslint rules for unused params that we intentionally want to keep (by prefixing `_`) 24d95fa2ecd72a6ae177c03e4f57f5429a9c4773

2024-01-19 11:57 UTC, TomRadford commented on src/stories/routes/CustomerAttributes.stories.svelte
> +  import { page } from '$app/stores';
resolved these props as part of 3085036

2024-01-19 11:58 UTC, TomRadford commented on src/components/Modal/Wrappers/PromptModal.svelte
> +  export let actionClick: (() => void) | ((parm: any) => void);
36fd29c235e2f83c7d2647c9313c5acef525163c

2024-01-19 11:59 UTC, TomRadford commented on src/components/Modal/Modal.svelte
> +    onOpenChange: ({ curr, next }) => {
e428ac4b86f3f260ed36b2343fdf275ca35a6716

2024-01-19 12:20 UTC, TomRadford commented on src/components/Modal/Wrappers/PromptModal.svelte
> +  export let disabled = false;
This is for input, made a story: 8d506e577c5919df2e3c95a8a233c60f502a6364  
Adding a confirm modal too

2024-01-19 13:07 UTC, TomRadford commented on src/components/Modal/Wrappers/PromptModal.svelte
> +  export let disabled = false;
Confirm modal:
37a2a6ab9e9b5aabc06c59432cda1d9a987fbbfa

2024-01-22 12:59 UTC, flumonion commented on src/components/Modal/Wrappers/PromptModal.svelte
> +  export let disabled = false;
These are both looking good.
Small note on the styling.

<img width="492" alt="Screenshot 2024-01-22 at 14 36 12" src="https://github.com/stock2shop/console_v2/assets/1546805/7aceef64-4344-423e-9ad7-1331df9aafbb">

remove the bottom border.
The vertical padding for the inner content should be equal on top and bottom.
My example is wrong...

<img width="488" alt="Screenshot 2024-01-22 at 14 27 52" src="https://github.com/stock2shop/console_v2/assets/1546805/3bf8281b-ad32-4b77-afab-4b2f81ebba21">

Since the content text in confirm is likely to be short, perhaps center align text?

2024-01-22 13:08 UTC, flumonion commented on src/components/Controls/FieldSelector/DynamicFieldSelector.svelte
> +  import { isValidContract } from '@/models/pricing-contracts/pricing-contract';
great.
Out of interest, why would you want to keep an unused param?

i.e.
this
```
export let selectCallback = (_: string) => {};
```
vs
```
export let selectCallback = () => {};
```

2024-01-22 13:43 UTC, TomRadford commented on src/components/Modal/Wrappers/PromptModal.svelte
> +  export let disabled = false;
The second image, PromptModal with center position prop, takes it's own slot so aligning text will happen in there :) 
![image](https://github.com/stock2shop/console_v2/assets/7515754/b112236c-9dd5-407c-8fc5-859f08b398fc)
The only case when this is used (ie: with center prop) is for ConfirmModal

2024-01-22 14:04 UTC, TomRadford commented on src/components/Modal/Wrappers/PromptModal.svelte
> +  export let disabled = false;
432f035229fe95082fcfe8edc229f05a7925badb 

![image](https://github.com/stock2shop/console_v2/assets/7515754/874ebb65-c714-476c-92db-5c5a657f2bac)

2024-01-22 14:07 UTC, TomRadford commented on src/components/Controls/FieldSelector/DynamicFieldSelector.svelte
> +  import { isValidContract } from '@/models/pricing-contracts/pricing-contract';
I did it as a sort of shorthand, 
instead of 
`export let selectCallback: ((val: string) => void) | undefined;`
and then having to:
```
if (selectCallback) {
	selectCallback(newValue); 
}
```

2024-01-22 14:12 UTC, flumonion commented on src/components/Modal/Wrappers/PromptModal.svelte
> +  export let disabled = false;
nice!

2024-01-23 07:17 UTC, matthampton-stock2shop commented on src/components/Attributes/Attributes.svelte
> +  $: customerData = createCustomerQuery(id, !isProduct);
RAther have a prop to tel it to render the skeleton

2024-01-23 14:55 UTC, flumonion commented on src/components/Connectors/ChannelMaster.svelte
> +    console.log($settings.isStale);
remove log?

2024-01-23 14:55 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +  import Btn from '@/components/form/Btn.svelte';
it seems we have lost the templates in the product attributes story?

2024-01-23 14:55 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +  import Btn from '@/components/form/Btn.svelte';
The attribute stuff is looking good

2024-01-23 14:55 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +  // Only render template data/ui if entity is product
small nit...
would you only render template ui if templateItems is not undefined?
just mentioning it...

2024-01-23 16:34 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +  // Only render template data/ui if entity is product
fixed to only render the `Assign Templates` button when templateItems is assigned 8e828669faddc017fc97b2a834e46ffcbc565943 
Hope that's what you meant.

2024-01-24 06:54 UTC, flumonion requested changes

2024-01-24 06:54 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +  import Table from '@/components/grids/ui/Table.svelte';
Still got some little gremlins here, sorry.

When deleting the "custom attribute" in your story, two attributes get deleted (string attribute and custom attribute)
<img width="861" alt="Screenshot 2024-01-24 at 08 21 13" src="https://github.com/stock2shop/console_v2/assets/1546805/c57c08af-dfea-4b46-8af0-8af6e6820d48">
<img width="863" alt="Screenshot 2024-01-24 at 08 21 19" src="https://github.com/stock2shop/console_v2/assets/1546805/26fe20af-03ba-4cad-96e8-2c26cb215701">

2024-01-24 06:54 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +  import AttributeModal from '@/components/Attributes/AttributeModal.svelte';
same as previous comment.
When adding a template then deleting one of the items from the template, all items in the template get removed.

2024-01-24 06:54 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +    meta = [...meta, newAttribute];
When adding a new attribute, if the keys match we end up with duplicates.
The `meta.key` is unique for any array of metas.

The desired behaviour is that it would update the list.

It might make sense to use a map and not a list for your meta?
for key comparison you could lowercase and trim the keys...

<img width="902" alt="Screenshot 2024-01-24 at 08 27 53" src="https://github.com/stock2shop/console_v2/assets/1546805/8a557bdd-7225-40fd-934e-7efd3e7f42e3">
<img width="864" alt="Screenshot 2024-01-24 at 08 28 01" src="https://github.com/stock2shop/console_v2/assets/1546805/30215907-718c-4fca-9422-296bce6516b6">

2024-01-24 06:54 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +    const requiredWithMissing = attributes.filter(
When an attribute is required and you try save it creates some popup below.
What would be nice is if we could introduce whats in the figma design for input errors.

Then the user knows what is missing.
Don't have to do it now but I feel this is a better user experience than the popup (used to show success normally or some fatal error)

<img width="268" alt="Screenshot 2024-01-24 at 08 40 45" src="https://github.com/stock2shop/console_v2/assets/1546805/3b912933-1c2e-4e7c-a1a8-cf3e0a7186ce">

2024-01-24 06:54 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +  export let templateItems: TemplateWithItems[] | undefined = undefined;
another small nit (which you can choose to use or lose)..

The code in this component would be a lot simpler if the templates stuff was another component, `AttributeTemplates`

e.g.
```
{#if templateItems}
<AttributeTemplates {templateItems} bind:meta />
{/if}
```
It renders the two template buttons.

Its job would be to add to the meta dictionary.
unchecking a template would remove all the meta from the dictionary if their value unassigned.

If there is shared functions between the `AttributeTemplates` and `Attributes` components, you could create a `attributes.ts` which has the data types and the functions to add/remove etc...

This composition idea is my preference but i am also happy to leave it as is.

2024-01-24 08:22 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +    meta = [...meta, newAttribute];
Added some checks:
fec518b9a526105210ccf7062deb033d3483926f
29eebe8d8dd5e4a3f0bba5f57a9d32e32d2e4f26

2024-01-24 08:39 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +  import AttributeModal from '@/components/Attributes/AttributeModal.svelte';
8006bc70ef39c5acd9af96fe9f7534e79c7c0bb6

2024-01-24 08:39 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +  import Table from '@/components/grids/ui/Table.svelte';
8006bc70ef39c5acd9af96fe9f7534e79c7c0bb6

2024-01-24 09:01 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +    const requiredWithMissing = attributes.filter(
Agreed, we're not doing validations yet but me and @matthampton-stock2shop discussed potentially using something like Superforms https://superforms.rocks/concepts/spa/ to handle validations and give user feedback on relevant inputs.

2024-01-24 09:04 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +    const requiredWithMissing = attributes.filter(
3d09534b38449a8a00dac1c06aabadcd27d10a47 - made a quick change to list the required items

2024-01-24 09:53 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +  export let templateItems: TemplateWithItems[] | undefined = undefined;
4c142eef0eef923b2a0fc588a894325eb9659fe9 cleans things up nicely :)

2024-01-24 12:28 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +    const requiredWithMissing = attributes.filter(
> Agreed, we're not doing validations yet (its P3 #319) so when we get there using something like superforms in spa mode https://superforms.rocks/concepts/spa/ will do the trick

perhaps, but this feels like overkill?
Could there just not be a state on our input controls that is an error state?

anyways, good for time being.

2024-01-24 12:29 UTC, flumonion approved these changes
yay!

2024-01-24 12:29 UTC, merged