Product details: Image uploads
stock2shop/console_v2 pull request #394
Opened 2024-01-22 11:13 UTC by TomRadford

2024-01-24 08:20 UTC, flumonion requested changes

2024-01-24 08:20 UTC, flumonion commented on src/components/Product/ProductDetails.svelte
> +    createUploadProductImageMutation
This pr is looking good.

Another small composition nit.

We have a `ProductImage` and a `ProductImageSelector`.
The logic for adding and removing images is sitting in the ProductDetails component, which is already pretty complicated?

What about shifting the adding / deleting of product images to the ProductImage component? You still invalidate the product query after the mutation?

2024-01-24 08:20 UTC, flumonion commented on src/components/Product/ProductDetails.svelte
> +          type="mini"
<img width="770" alt="Screenshot 2024-01-24 at 10 07 34" src="https://github.com/stock2shop/console_v2/assets/1546805/6e46bfac-3519-49c1-b6d6-e1cbc33e6150">

2024-01-24 08:20 UTC, flumonion commented on src/components/Product/ProductDetails.svelte
> +    createUploadProductImageMutation
on second thoughts....
Would it not make sense to have `Controls/Image` component?
The `ProductImage` can use it (so can displaying an image on product page and in lists etc).

The Image would be the same as the ProductImage except if no data is given it could display placeholder image. You could define what size you want displayed (since our thumbnails sizes are fixed) and it could allow for zooming on original etc (not suggesting doing that now).

2024-01-24 12:38 UTC, TomRadford commented on src/components/Product/ProductDetails.svelte
> +          type="mini"
So strange that this one seems to be the TS LSP that hadn't caught up, seems fine on a reload:
<img width="385" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/00585712-c219-431d-ba05-eb11c007f36d">

2024-01-29 13:13 UTC, TomRadford commented
Image not resolving (on:error handler for img):
<img width="339" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/4919ab51-2224-4472-b4d7-290ff9b83764">
Placeholder:
<img width="286" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/c20bb1b3-599c-4509-adc0-1c9331b047fb">

2024-01-31 08:02 UTC, matthampton-stock2shop commented on src/components/Product/ProductDetails.svelte
> +    selectedImage = img;
I think we should introduce one more component that has the product image and selector in it and manages the selectedImage state

2024-02-01 11:40 UTC, TomRadford commented on src/components/Product/ProductImageSelector.svelte
> +  import type ImageType from '@/models/image';
839aa466939eb79275377c153bd83525554fad49

2024-02-01 11:41 UTC, TomRadford commented on src/components/Product/ProductImageSelector.svelte
> +
4440aed0d7f052ab58362d6adbf5315509f792bf

2024-02-01 12:50 UTC, TomRadford commented on src/components/Product/ProductDetails.svelte
> +    selectedImage = img;
ce71202b9d7b73392f1d82b409cc6437a72f22db

2024-02-01 13:22 UTC, TomRadford commented on src/components/Product/ProductImageSelector.svelte
> +<script lang="ts">
https://github.com/stock2shop/console_v2/commit/839aa466939eb79275377c153bd83525554fad49

2024-02-01 13:24 UTC, TomRadford commented on package.json
> -    "svelte-select": "^4.4.7",
yeah this is what has been replaced with our own Select component, 
must have forgotten to remove it previously

2024-02-01 13:30 UTC, TomRadford commented on src/components/Import/FileSelector.svelte
> + Mini - Small dropzone-style ui
this seems to be an api bug, happening in console v1 
<img width="292" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/cec64c09-e6e3-40ae-aa3c-c46eedc3dc8a">

Strangely, also happening with a 4.2mb jpeg.

2024-02-02 13:11 UTC, matthampton-stock2shop requested changes

2024-02-02 13:11 UTC, matthampton-stock2shop commented on src/components/Controls/Image.svelte
> +    class={cn('h-full w-full object-contain', { hidden: isLoading }, className)}
Wondering if we can do something similar for the product list page: (is it using the Image component?):

<img width="312" alt="image" src="https://github.com/stock2shop/console_v2/assets/124143173/e0295472-1ee4-4a82-99db-0f01499e4f15">

Barbie's head chopped off there

2024-02-02 13:11 UTC, matthampton-stock2shop commented on src/components/Product/ProductImageGroup.svelte
> +    console.log(newImages);
debugging?

2024-02-02 13:11 UTC, matthampton-stock2shop commented on src/components/Controls/Image.svelte
>  {:else}
Also, there is some slightly funky layout stuff going on where there is an image selected for a variant:

<img width="229" alt="image" src="https://github.com/stock2shop/console_v2/assets/124143173/4d50fb1e-b5a8-4b4b-975f-6459bc9f7775">

Not quite enough space there, I guess, but it does look funny with the starting character getting chopped

2024-02-02 13:11 UTC, matthampton-stock2shop commented on src/components/Import/FileSelector.svelte
> + Mini - Small dropzone-style ui
Logged: https://github.com/stock2shop/app/issues/2432

2024-02-02 13:11 UTC, matthampton-stock2shop commented on src/components/Product/ProductImageSelector.svelte
> +
This currently doesn't show a placeholder (when there isn't a variant image) - it shows the first... Feels a bit wrong

2024-02-02 14:57 UTC, TomRadford commented on src/components/Product/ProductImageGroup.svelte
> +    console.log(newImages);
3554652e25fead2f7d6cb496f851420db17c73dc

2024-02-02 15:01 UTC, TomRadford commented on src/components/Controls/Image.svelte
> +    class={cn('h-full w-full object-contain', { hidden: isLoading }, className)}
it is using the new Image component.
Do you mind sending this image of barbie, I want to double check my side.
Seems okay with a image I pulled from:
![image](https://github.com/stock2shop/console_v2/assets/7515754/9eec1628-925d-4f7e-96ad-7ad42e72867d)

2024-02-02 15:07 UTC, TomRadford commented on src/components/Controls/Image.svelte
>  {:else}
35f55293c678c1fd858be91cbd1139122d5925ad

2024-02-02 15:07 UTC, TomRadford commented on src/components/Product/ProductImageSelector.svelte
> +
https://github.com/stock2shop/console_v2/commit/3554652e25fead2f7d6cb496f851420db17c73dc

2024-02-05 06:39 UTC, matthampton-stock2shop commented on src/components/Controls/Image.svelte
> +    class={cn('h-full w-full object-contain', { hidden: isLoading }, className)}
![barbie](https://github.com/stock2shop/console_v2/assets/124143173/8baab3c1-7cd3-471a-b101-3952ff660617)

2024-02-06 09:52 UTC, TomRadford commented on src/components/Controls/Image.svelte
> +    class={cn('h-full w-full object-contain', { hidden: isLoading }, className)}
deba08c0c8a8fd0b28770e268b02ce418440840d

2024-02-06 16:08 UTC, TomRadford commented
Resolved

- Headers spacing fixes
- Image in image group must be full width (and center)
- Ellipse on the sku
- Upload on first
- Maybe scroll icon
- Variant image can be 50x50
- Size renamed to src prop for Image component

2024-02-07 10:55 UTC, matthampton-stock2shop approved these changes

2024-02-07 10:56 UTC, merged