logs to table, button sizing and icons
stock2shop/console_v2 pull request #396
Opened 2024-01-23 10:20 UTC by flumonion

2024-01-23 12:22 UTC, TomRadford requested changes

2024-01-23 12:22 UTC, TomRadford commented on src/components/Controls/Text.svelte
> +  <div use:melt={$content} class="z-10 rounded bg-neutral-700 shadow">
Since we're using this tooltip in Button too, we could make a TooltipContent or TooltipInternal:
```svelte
<script lang="ts">
  import { createTooltip, melt } from '@melt-ui/svelte';
  import { fade } from 'svelte/transition';

  // At the expense of initialising an unused tooltip builder,
  // this allows for easy type inference
  const {
    elements: { content: contentInternal, arrow: arrowInternal }
  } = createTooltip();

  export let content = contentInternal;
  export let arrow = arrowInternal;
</script>

<div
  use:melt={$content}
  transition:fade={{ duration: 100 }}
  class="z-10 rounded bg-neutral-700 shadow"
>
  <div use:melt={$arrow} />
  <p class="px-4 py-1 text-regular font-normal leading-6 text-white"><slot /></p>
</div>

```

Then you could use it here as follows:
```svelte
<!-- Tooltip Content-->
{#if tooltip && $open}
  <TooltipContent content={content} arrow={arrow}>{tooltip}</Tmp>
 {/if}
```

2024-01-23 12:22 UTC, TomRadford commented on src/components/Icons/Icon.svelte
> +    'i-10': 'h-10 w-10'
makes sense to me 👌

2024-01-23 14:24 UTC, TomRadford requested changes

2024-01-23 14:24 UTC, TomRadford commented on src/components/Controls/Button.svelte
>    )}
I'm curious how we can set w-full for the button when we want it to fill a container.

2024-01-24 06:07 UTC, flumonion commented on src/components/Controls/Text.svelte
> +  <div use:melt={$content} class="z-10 rounded bg-neutral-700 shadow">
nice, good find!

https://github.com/stock2shop/console_v2/pull/396/commits/92c82f7c35aec629be1e0139d227c60a75963f04

Lets monitor to see if creating two instances of tooltip is a performance issue.

2024-01-24 06:15 UTC, flumonion commented on src/components/Controls/Button.svelte
>    )}
added example and custom class back

https://github.com/stock2shop/console_v2/pull/396/commits/128321409756535c52e3ada074310dbd98654dd4

2024-01-24 06:47 UTC, TomRadford approved these changes

2024-01-24 06:47 UTC, merged