Logs, various bug fixes
stock2shop/console_v2 pull request #454
Opened 2024-02-06 13:03 UTC by flumonion

2024-02-21 11:56 UTC, TomRadford requested changes

2024-02-21 11:56 UTC, TomRadford commented on src/components/Controls/Table/TableRows.svelte
> +            on:click={() => dispatch('rowClick', row)}
we might also want to move rowClick to a callback prop

2024-02-21 11:56 UTC, TomRadford commented on src/components/Queue/QueueErrorTableAction.svelte
> +    queryClient.resetQueries(['queue-items']);
maybe rather just make params optional in queueKeys.items
ie:
```ts
  items: (params?: QueueSearchParams) => ['queue-items', ...(params ? [params] : [])]
  ```
would do the trick

2024-02-21 13:34 UTC, flumonion commented on src/components/Logs/Logs.svelte
https://github.com/stock2shop/console_v2/pull/454/commits/e268d3baab12ae812e7810e9077027eb2ccc5739

2024-02-22 07:27 UTC, flumonion commented on src/components/Controls/Table/TablePagination.svelte
> +      dispatch('paginated', tableProps.pagination);
https://github.com/stock2shop/console_v2/pull/454/commits/49759025ac13548037b984462e23b8589dfc096f

Although there is an issue...
The onPagination function is fired when the size `Select` is changed. However, the Select component registers a onChange event when it first loads, not ideal. 
I have made a change in this pr to solve this, but it does create another side effect, [see this](https://github.com/stock2shop/console_v2/pull/454/commits/49759025ac13548037b984462e23b8589dfc096f#diff-6a332c70a2e4103b1b36e935338edab5179680113bb6b442726159cb301721e8R107).

I think the select might be better off using the $selected value to set the bound prop value.
In melt they call this "syncing state"
https://melt-ui.com/docs/controlled#syncing-state

Also, it seems that binding a nested object is not changing its value.

2024-02-22 07:39 UTC, flumonion commented on src/components/Queue/QueueError.svelte
> +    queryClient.resetQueries(queueKeys.items(searchParams));
I don't believe this is correct...
https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientresetqueries
It will refetch.

2024-02-22 07:48 UTC, flumonion commented on src/components/Queue/QueueErrorTableAction.svelte
> +    queryClient.resetQueries(['queue-items']);
https://github.com/stock2shop/console_v2/pull/454/commits/d6255c561b0bde1884885e52fee4fbe71279b474

2024-02-22 09:35 UTC, flumonion commented on src/components/Controls/Table/TableRows.svelte
> +            on:click={() => dispatch('rowClick', row)}
https://github.com/stock2shop/console_v2/pull/454/commits/e13fbe1bad6b7a6ce001b9ea8aa142d003361e23

2024-02-23 13:37 UTC, TomRadford commented on src/components/Queue/QueueError.svelte
> +    queryClient.resetQueries(queueKeys.items(searchParams));
looks good! 

however,
resetQueries seems to just be a variation of refetchQueries that sets to initialData (if there is any set in the QueryOptions) and then refetches:
<img width="822" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/9497bf73-0764-44e6-9507-a5d0131321ad">
so, in this case, resetQueries === refetchQueries.
<img width="852" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/3fab9121-059a-40ed-86bb-06cff8f81b21">
however, having looked at this again, invalidation is actually what we need here: 
`queryClient.invalidateQueries(queueKeys.items());`

2024-02-27 09:52 UTC, TomRadford commented on src/components/Controls/Table/TablePagination.svelte
> +      dispatch('paginated', tableProps.pagination);
I'd like to get this merged with the following fix:
e85191106a7e30731fc7086ae32e596cfb97a4e9

2024-02-27 09:55 UTC, TomRadford approved these changes
Happy to merge with my one small tweak

2024-02-28 09:29 UTC, TomRadford approved these changes

2024-02-28 09:30 UTC, merged