Styling Fixes and Refactoring
stock2shop/console_v2 pull request #467
Opened 2024-02-16 07:57 UTC by TomRadford

2024-02-16 08:11 UTC, TomRadford commented on tailwind.config.js
> -        mono: ['PTMono-Regular', 'monospace']
this wasnt in design, we seem to just use Public sans (same font) for monospace/numbers:
<img width="1903" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/75a5aa9c-2764-490d-9f33-4ede29a57e51">

2024-02-19 07:38 UTC, flumonion requested changes

2024-02-19 07:38 UTC, flumonion commented on src/components/Attributes/Attributes.svelte
> +      <h4 class="mb-4 text-neutral-700">Current Attributes</h4>
should the text colour not be in the h4 default styling?

2024-02-19 07:38 UTC, flumonion commented on src/components/Customer/SimpleCustomerDetail.svelte
> +        <h4 class="mb-4 text-neutral-700">Details</h4>
text colour in default h4 style?

2024-02-19 07:38 UTC, flumonion commented on src/components/Orders/CustomerSummary.svelte
> +  <h4 class="mb-4 text-neutral-700">Customer Details</h4>
h4 colour

2024-02-19 07:38 UTC, flumonion commented on src/components/Orders/FulfillmentDetails.svelte
> +  <h4 class="mb-4 text-neutral-700">Fulfillment Details</h4>
h4 colour

2024-02-19 07:38 UTC, flumonion commented on src/components/Orders/FulfillmentModal.svelte
> +        <h4 class="mb-4 text-neutral-700">Fulfillment</h4>
h4 colour

2024-02-19 07:38 UTC, flumonion commented on src/components/Orders/OrderDetails.svelte
> +  <h4 class="mb-4 text-neutral-700">Order Details</h4>
h4 colour

2024-02-19 07:38 UTC, flumonion commented on src/components/PageHeader.svelte
> +        inputClass={cn('font-bold text-2xl leading-[1.875rem]', additionalClasses)}
how come leading is different on these headings?
Should the leading always not be the same for all H's?

2024-02-19 07:38 UTC, flumonion commented on src/components/Product/ProductChannels.svelte
> +      <h4 class="mb-4 text-neutral-700">Channels</h4>
h4 colour

2024-02-19 07:38 UTC, flumonion commented on src/components/Segments/SegmentsType.svelte
> +      <h4 class="my-auto mb-4 text-neutral-700">
h4 colour

2024-02-19 07:38 UTC, flumonion commented on src/components/Settings/SettingsNav.svelte
> +  <h4 class="mb-4 text-neutral-700">Settings</h4>
h4 colour

2024-02-19 07:38 UTC, flumonion commented on src/components/Settings/User.svelte
> +  <h4 class="mb-4 text-neutral-700">Contact Details</h4>
h4 colour

2024-02-19 12:16 UTC, TomRadford commented on src/components/Controls/Search.svelte
> +  export let onSearch = (s: string) => {};
Keeping as-is as per our chat on KB:
there's a really interesting read on https://svelte-5-preview.vercel.app/docs/event-handlers#why-the-change about why accepting callback props over events is a nicer pattern. Since using callback props is something we can do now in v4, I'm refactoring/utilising them over svelte event handlers because the type safety benefits by explicitly defining events as callback props seems like an easy win 🙌

2024-02-19 13:17 UTC, TomRadford commented on src/components/Attributes/Attributes.svelte
> +      <h4 class="mb-4 text-neutral-700">Current Attributes</h4>
looks like the default is `text-neutral-800` and `text-neutral-700` is specified from some of these titles. Seeing as we use mb-4 text-neutral-700 in quite a few places, refactored into a SubHeading component:
461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:17 UTC, TomRadford commented on src/components/Customer/SimpleCustomerDetail.svelte
> +        <h4 class="mb-4 text-neutral-700">Details</h4>
same as above 461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:18 UTC, TomRadford commented on src/components/Orders/CustomerSummary.svelte
> +  <h4 class="mb-4 text-neutral-700">Customer Details</h4>
same as above 461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:18 UTC, TomRadford commented on src/components/Orders/FulfillmentDetails.svelte
> +  <h4 class="mb-4 text-neutral-700">Fulfillment Details</h4>
same as above 461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:18 UTC, TomRadford commented on src/components/Orders/FulfillmentModal.svelte
> +        <h4 class="mb-4 text-neutral-700">Fulfillment</h4>
same as above 461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:18 UTC, TomRadford commented on src/components/Orders/OrderDetails.svelte
> +  <h4 class="mb-4 text-neutral-700">Order Details</h4>
same as above 461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:28 UTC, TomRadford commented on src/components/PageHeader.svelte
> +        inputClass={cn('font-bold text-2xl leading-[1.875rem]', additionalClasses)}
leading wasnt doing anything here, removed
b327d1d7b181b21e5585ac751dc6094e84b1233c

2024-02-19 13:28 UTC, TomRadford commented on src/components/Product/ProductChannels.svelte
> +      <h4 class="mb-4 text-neutral-700">Channels</h4>
same as above https://github.com/stock2shop/console_v2/commit/461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:28 UTC, TomRadford commented on src/components/Settings/SettingsNav.svelte
> +  <h4 class="mb-4 text-neutral-700">Settings</h4>
same as above https://github.com/stock2shop/console_v2/commit/461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:28 UTC, TomRadford commented on src/components/Settings/User.svelte
> +  <h4 class="mb-4 text-neutral-700">Contact Details</h4>
same as above https://github.com/stock2shop/console_v2/commit/461a4b0898a80158a7904f92aaccfa4fda826c22

2024-02-19 13:31 UTC, TomRadford commented on src/components/Controls/Toggle.svelte
> +      'flex min-h-[40px] items-center justify-between gap-2 rounded border border-neutral-200 px-3':
https://bradfrost.com/blog/post/atomic-web-design/ Im trying to start thinking of our components in these terms a bit more  🧐

2024-02-19 14:00 UTC, flumonion commented on src/components/Controls/Toggle.svelte
> +      'flex min-h-[40px] items-center justify-between gap-2 rounded border border-neutral-200 px-3':
Great, this works.
I am going to approve/merge this one.
One nit here is that "ToggleDetail" is an odd name for the component (for me anyways...).
Its a toggle form input "field" which includes a label?
Should it not be `ToggleField`? or in controls we could have a directory called "formFields" and have it in there?

2024-02-19 14:01 UTC, flumonion submitted a review, later dismissed

2024-02-19 14:05 UTC, flumonion approved these changes

2024-02-19 14:05 UTC, merged