Product Channels Fixes
stock2shop/console_v2 pull request #473
Opened 2024-02-21 09:23 UTC by TomRadford

2024-02-21 09:28 UTC, TomRadford commented on src/models/channels/system-channel.ts
> -    this.active = active ?? 0;
this one of the sources of that funky boolean being 0/1 issue

2024-02-21 09:33 UTC, TomRadford commented on src/components/Product/ProductChannels.svelte
> +  let productVariantChannels: (
we use this var to store only required variant channels. We push to it from processChannel. 
It's a little hard to follow but seems to work well with the tweaks I made. Just need to reset it whenever re-running the VM creator query.

2024-02-22 08:03 UTC, Ayano2000 commented on src/components/Header/Tabs.svelte
> +  export let allowNavigation = () => true;
@TomRadford is going to remove the `allowNavigation` in favor of `beforeNavigation`

2024-02-22 08:06 UTC, Ayano2000 requested changes
See: https://github.com/stock2shop/console_v2/pull/473/files#r1498814715

2024-02-22 13:55 UTC, matthampton-stock2shop commented on src/components/Product/ProductChannels.svelte
> +          channel_variant_code: cv.channel_variant_code
I had some odd behaviour when the text fields where blank (i.e. cv.channel_variant_code === '') - where it would create a row in the db with a blank value - bit then it would not delete them.

I think we should do something about this

2024-02-23 08:40 UTC, TomRadford commented on src/components/Header/Tabs.svelte
> +  export let allowNavigation = () => true;
927ec7a0eb949ff70905d786ddf4a806f0318a74

2024-02-23 09:11 UTC, TomRadford commented on src/queries/channelSources.query.ts
> +export const createChannelSourceQuery = (id: number, enabled = true) =>
Going to be quite complex to get this to work because of all the data mapping going on. I think we can do this one when the new API is in place.

2024-02-23 09:50 UTC, TomRadford commented on src/routes/(app)/customer/[id]/+layout.svelte
> +        continueAfterOnSave = await $onSaveChanges();
hmm the purpose of onSaveChanges returning false it to tell the save function to not run the rest of the code. A failure is indicated with a throw

2024-02-23 09:51 UTC, TomRadford commented on src/routes/(app)/product/[id]/+layout.svelte
> +    $product.workingCopy = cloneDeep($product.serverVersion);
927ec7a0eb949ff70905d786ddf4a806f0318a74

2024-02-23 09:52 UTC, TomRadford commented on src/routes/(app)/customer/[id]/+layout.svelte
> +        continueAfterOnSave = await $onSaveChanges();
246f69c567e18c8bd4d1d61ae8b61f8f2cf49f11

2024-02-23 09:53 UTC, TomRadford commented on src/routes/(app)/product/[id]/+layout.svelte
> +  const allChangesMade = writable(false);
1d74e3b96e70d1b4900ef4f72329cdaaad7e283f

2024-02-23 12:26 UTC, TomRadford commented on src/routes/(app)/product/[id]/+layout.svelte
> +        enabled: $allChangesMade || !$isSaving,
yes, resolved

2024-02-23 12:40 UTC, TomRadford commented on src/components/Product/ProductChannels.svelte
> +          channel_variant_code: cv.channel_variant_code
b68b4732964116bfafb8a55f734b26598348e79c

2024-02-28 13:33 UTC, Ayano2000 approved these changes
LGTM

2024-02-29 14:25 UTC, merged