Upgrade to TanStack Query V5
stock2shop/console_v2 pull request #477
Opened 2024-02-26 12:41 UTC by TomRadford

2024-03-02 12:58 UTC, flumonion requested changes
There seem to be conflicts with master, can youy please resolve these.

Also the Tanstack dev tools is missing? Or do I need to do something different now to bring them up?

2024-03-04 09:13 UTC, TomRadford commented on package.json
> +    "@tanstack/svelte-query-devtools": "^5.24.1",
should be in devtools 2b8f50f0d1320fa9eb3f8736f5e369129757fbb9

2024-03-04 09:22 UTC, TomRadford commented on package.json
> +    "@tanstack/svelte-query-devtools": "^5.24.1",
should be good.. I moved the query devtool icon to the right side of the screen because it was blocking the settings icon on the left:
<img width="1063" alt="image" src="https://github.com/stock2shop/console_v2/assets/7515754/9b1ecf9e-340c-49ff-ab50-d58eebf91e07">

2024-03-04 09:41 UTC, flumonion approved these changes

2024-03-04 09:42 UTC, merged