Bind Log & Queue query params to stores
stock2shop/console_v2 pull request #491
Opened 2024-03-01 12:30 UTC by TomRadford

2024-03-03 13:27 UTC, flumonion requested changes
The code all makes sense and it does make it easier working with url params, great!
Just a few minor things on the ES component composition.

2024-03-03 13:27 UTC, flumonion commented on src/components/ES/Aggregation.svelte
> +  export let paramsStore: Writable<Record<string, string | undefined>>;
Our ES components now require url state?
Should url state not be managed by a page layout or a component that ties together the different es components?

What if we wanted two queries on one page?

I am happy for you to remove events in favour of a callback, but not sure they should control the url directly.

For the logs, the log component can do all of that?
i.e. if a filter is removed, it can remove from url?

2024-03-03 13:27 UTC, flumonion commented on src/components/ES/Aggregation.svelte
> +  export let paramsStore: Writable<Record<string, string | undefined>>;
What do you think about the `logs.svelte` binding `aggs`?
Means we don't need a callback (or event).
it can then do:-

```ts
$: if(aggs) {
    // change $logParamsStore
  }
```

Basically, the same as you have done with the search.

Other ES components we will have in the future (that are not using url):-

`Results` -> using table
`Pagination` -> using table pagination
`Sorting`

and so on...

2024-03-03 13:27 UTC, flumonion commented on src/components/ES/Aggregations.svelte
> +    aggs.forEach((_, i) => {
same as above comment. Maybe this should be controlled by the parent component?

2024-03-03 13:27 UTC, flumonion commented on src/components/Logs/Logs.svelte
> +  const onSearch = (search: string) => {
yes, i like this. very clean....
add in same for aggs and anything that changes based on url.

If you wanted to make this page easier to test with storybook, you could move all of this one level up to the `routes/logs.svelte`. It feels to me that is where all the routing and loading of data belongs.

But that is just a preference, probably fine where it is for now?
What do you think?

2024-03-03 13:27 UTC, flumonion commented on src/models/logs/log-search-params.ts
> +  search?: string;
do we still need this type if we have the new query params one?

2024-03-03 13:27 UTC, flumonion commented on src/utils/stores/queryParams.ts
> +export const tokenParam = queryParam('token', ssp.string());
yes, i much prefer this file being called what it is :)

2024-03-03 13:31 UTC, flumonion requested changes

2024-03-03 13:31 UTC, flumonion commented on src/utils/stores/queryParams.ts
> +    size: ssp.string('10000'),
OOPS!

2024-03-04 09:58 UTC, TomRadford commented on src/utils/stores/queryParams.ts
> +    size: ssp.string('10000'),
aa39a69de6e95c441e1dd376458af1ceced4a4ae

2024-03-04 10:33 UTC, TomRadford commented on src/models/logs/log-search-params.ts
> +  search?: string;
6c0c5570aaf5487d71ae11b6d5cea4b6a94a2c1f

Just infered rather

2024-03-04 12:49 UTC, TomRadford commented on src/components/ES/Aggregation.svelte
> +  export let paramsStore: Writable<Record<string, string | undefined>>;
We no longer make any changes to `aggs`, (in the value property) since we now make these value changes in the store. I can try to add value back and then change $logParamStore value in Logs. But I'm not sure that's what you mean. 

Also fyi as long as URLSearchParam key's are not the same we can have as many queryParameters stores as we like.

2024-03-05 10:30 UTC, TomRadford commented on src/components/ES/Aggregation.svelte
> +  export let paramsStore: Writable<Record<string, string | undefined>>;
Moved the store out of aggs, making things nice and simple using the add/remove/reset callback props 10f230e4148042c8f8de9c5c35cbc9f17c21594d

2024-03-05 20:20 UTC, flumonion requested changes
Looking good. Just my point about the values in the aggs.
Probably worth having a look before merge...

2024-03-05 20:20 UTC, flumonion commented on src/models/es/aggregations.ts
> -  value: string;
Are you wanting to remove the value from the aggregation, even though it no longer is bound to query params?

It useful to know if an agg has a value set (especially if we want to build ES queries from it) that is why I added value there.

p.s. The story for this no longer works when clicking a agg.

Maybe you want to set the list of query params from the aggs like you do with the search and the other query params?
You could 2 way bind aggs.

2024-03-12 09:55 UTC, TomRadford commented
Closing this off due to https://github.com/stock2shop/console_v2/pull/502

2024-03-12 09:55 UTC, TomRadford commented
Closing this off due to https://github.com/stock2shop/console_v2/pull/502

2024-03-12 09:55 UTC, closed without merging