Justin krs/orders
stock2shop/console_v2 pull request #85
Opened 2023-03-16 20:28 UTC by justinengle-krs

Orders List tab
https://trello.com/c/DYmvh9ko/38-orders-list
https://trello.com/c/7rvzdFzb/41-orders-search
https://trello.com/c/jwvsjGsH/42-order-multiselect

**Notes:**
- As discussed with Matt, the styling on the order status is not viable or worth it, as this is a random string based on the channel.
- Column configurator not needed according to Chris.

**Chromatic build**
https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=26

**Zeplin:**
![image](https://user-images.githubusercontent.com/125956275/225736530-04ce9e8d-0c6c-417f-b0c3-207b92ef35fd.png)

**Implementation:**
![image](https://user-images.githubusercontent.com/125956275/225745791-509ee1a6-c1e2-4892-a511-8c7272ad25fd.png)

2023-03-16 20:43 UTC, justinengle-krs commented on src/env/local/persistent.ts
> +    [ElasticSearchIndex.CUSTOMER_ORDERS]: {
We don't want the column configurator  on orders screen to affect the customer/orders screen

2023-03-17 14:15 UTC, TheSuperRealJP commented on src/components/Customer/Orders.svelte
> +    <PageHeader title="{customerVersionControlled.workingCopy.first_name} {customerVersionControlled.workingCopy.last_name}" hasBackButton={true}>
Is the intended plan to repeat this PageHeader for each one of the Customer tabs? It feels like this belongs on Customer > Details.svelte. It might be out of scope of this PR, but worth considering before this header is repeated again for Attributes, Segments, Data Sync, etc.

2023-03-17 14:21 UTC, TheSuperRealJP commented on src/components/Customer/Orders.svelte
> +      alert(apiResult.error);
I know this may be moved based on my later comment, but does this "alert" does not stop the flow of `saveChanges` when `!apiResult.result`. You'll still get a `alert('Customer saved');` which is wrong.

2023-03-17 14:23 UTC, TheSuperRealJP requested changes
Orders.svelte inherits too much repeated code (HTML &  TS) from CustomerDetail.svelte.

2023-03-20 08:13 UTC, justinengle-krs commented
> Orders.svelte inherits too much repeated code (HTML & TS) from CustomerDetail.svelte.

Good point. I have made changes to resolve this.

CustomerMaster.svelte has been created. It contains all logic and requirements for handling the container of the page:
![image](https://user-images.githubusercontent.com/125956275/226282296-1055a2aa-4c93-473f-b445-29b628719a88.png)

CustomerDetail and Orders only does whats specific to that portion.

CustomerMaster implements its own SaveChanges which Saves the customer, and then fires off a passed in delegate function to execute any custom save logic for the current page

2023-03-20 08:14 UTC, justinengle-krs commented on src/components/Customer/Orders.svelte
> +    <PageHeader title="{customerVersionControlled.workingCopy.first_name} {customerVersionControlled.workingCopy.last_name}" hasBackButton={true}>
covered in reduce duplications

2023-03-23 10:19 UTC, justinengle-krs commented
> @justinengle-krs FYI
> 
> Issue: saving customer while on tab other than "Details" causes blank screen afterwards.
> 
> Reproduce steps:
> 
> 1. Go to /#/customer/5676648/details
> 2. Save changes and confirm page reloads just fine after save.
> 3. Go to Orders tab.
> 4. Save changes and confirm spinner animation and success alert.
> 5. See blank page. Browser "back" also doesn't do anything (URL is updated though)
> 
> Cause: Likely this error in console ![image](https://user-images.githubusercontent.com/22594341/226907542-ecec43b8-5b8c-4f7a-83ed-b989f2e987e2.png)

Good catch thanks. Resolved

2023-03-23 10:36 UTC, TheSuperRealJP approved these changes

2023-03-23 11:21 UTC, matthampton-stock2shop commented on src/components/Customer/CustomerDetail.svelte
>    import type ChannelUsersRepo from '@/repos/channel-users-repo';
Chromatic change expected? https://www.chromatic.com/test?appId=63ef6cddab1dec384359e1cd&id=641c33b2d963e7d76245eddc

2023-03-23 11:28 UTC, justinengle-krs commented on src/components/Customer/CustomerDetail.svelte
>    import type ChannelUsersRepo from '@/repos/channel-users-repo';
In the zeplin the warning colour seems to be #f5931c. So this is correct?

See here: https://app.zeplin.io/project/629fb41be1a2021104a7cae0/screen/63f8ebaf47d0ec1035743b7b

2023-03-23 11:47 UTC, matthampton-stock2shop requested changes

2023-03-23 11:47 UTC, matthampton-stock2shop commented on src/routes/CustomerOrders.svelte
> +<Orders customerId={params.id} {customersRepo} />
Could we add a storybook screen for this?

e.g. to show something like the one you have in the description

![image](https://user-images.githubusercontent.com/125956275/225745791-509ee1a6-c1e2-4892-a511-8c7272ad25fd.png)

2023-03-23 11:47 UTC, matthampton-stock2shop commented on src/env/common/columns/orderColumns.ts
> -    label: 'Channel Order Code',
I think we should leave this label as 'Channel Order Code' (is it is not the 'Channel' - it is a code for each each order e.g. #2123)..

(And we are happy for this to be the column that is showing rather than Channel as in the design)

2023-03-23 11:47 UTC, matthampton-stock2shop commented on src/components/Customer/CustomerDetail.svelte
>    import type ChannelUsersRepo from '@/repos/channel-users-repo';
Oops- I was seeing the green 'diff' highlighting and it looked like the color had changed to green!! Sorry!

2023-03-23 11:47 UTC, matthampton-stock2shop commented on src/env/local/persistent.ts
> +    [ElasticSearchIndex.CUSTOMER_ORDERS]: {
Makes sense - I'm assuming somewhere there must be some knowledge that the CUSTOMER_ORDERS is not an actual elastic search index though (i.e. that it needs to query the ORDERS index on the backend) .. Can you point me to that code? (Sorry if it was obvious)

2023-03-23 12:16 UTC, justinengle-krs commented
@matthampton-stock2shop Can't seem to reply on the ElasticSearch question. On Customer/Orders.svelte we use ElasticSearchIndex.ORDERS to query the API

2023-03-23 12:23 UTC, matthampton-stock2shop commented
> @matthampton-stock2shop Can't seem to reply on the ElasticSearch question. On Customer/Orders.svelte we use ElasticSearchIndex.ORDERS to query the API

Ok - so when is ElasticSearchIndex.CUSTOMER_ORDERS actually used then?

2023-03-23 12:36 UTC, justinengle-krs commented
> > @matthampton-stock2shop Can't seem to reply on the ElasticSearch question. On Customer/Orders.svelte we use ElasticSearchIndex.ORDERS to query the API
> 
> Ok - so when is ElasticSearchIndex.CUSTOMER_ORDERS actually used then?

s2sStore.ts is where its used to retrieve the columns. 

There's a mapColumns which seems to "inner join" the system config with the persistent config.

Both which have a "key" for CUSTOMER_ORDERS

See: /common/local/system.ts and /common/local/persistent.ts

2023-03-23 12:58 UTC, matthampton-stock2shop commented on src/env/local/persistent.ts
> +    [ElasticSearchIndex.CUSTOMER_ORDERS]: {
Oh, ok - got it

2023-03-23 20:52 UTC, justinengle-krs commented on src/routes/CustomerOrders.svelte
> +<Orders customerId={params.id} {customersRepo} />
DOne

2023-03-23 20:52 UTC, justinengle-krs commented on src/env/common/columns/orderColumns.ts
> -    label: 'Channel Order Code',
Done

2023-03-24 10:15 UTC, matthampton-stock2shop approved these changes

2023-03-24 10:15 UTC, merged