Justin krs/order detail-Customer details and notes only
stock2shop/console_v2 pull request #89
Opened 2023-03-29 11:50 UTC by justinengle-krs

Order detail:
**customer details and notes only**

Zeplin:
![image](https://user-images.githubusercontent.com/125956275/228525103-e5ca1798-59a8-4c9c-85d2-4ce25d0cfc2d.png)

Implemenation:
![image](https://user-images.githubusercontent.com/125956275/228525907-8c2f9237-4ac9-42a6-bd31-6ab59e79d75c.png)

2023-03-31 13:51 UTC, matthampton-stock2shop requested changes

2023-03-31 13:51 UTC, matthampton-stock2shop commented on src/stories/routes/85-Order.stories.svelte
> +<script lang="ts">
I made a couple of comments on the chromatic build:

https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=31

2023-03-31 13:51 UTC, matthampton-stock2shop commented on src/stories/routes/85-Order.stories.svelte
> +<script lang="ts">
(see the red ones)

2023-03-31 13:51 UTC, matthampton-stock2shop commented on src/models/sources/source.ts
> +  source_order_code: string;
This seems a bit odd to me - do we put these values in to a 'source' object in an order? Maybe we can rather make a subclass of this called "order_source" or something like that? And use that one for an order...

2023-03-31 13:51 UTC, matthampton-stock2shop commented on src/models/sources/source.ts
> +  source_order_code: string;
In fact! In our database this is a different table, called - "order_source"

![image](https://user-images.githubusercontent.com/124143173/229138263-f5e57549-adbc-46be-9e0f-c26ffaf1f3d1.png)

It doesn't have all of the other properties of a source, though - it is just a link - and stores the idenfifier of this order for that source.

So I think it makes more sense to create a new model for this - rather than extending the existing source model....

2023-03-31 13:52 UTC, matthampton-stock2shop commented on src/models/customer/customer.ts
> +    this.createdDisplay = `${createdDate.toDateString()} ${createdDate.toLocaleTimeString()}`;
Also - does it make sense for this to be in the model? It feels like a view responsibility to me...

2023-03-31 13:59 UTC, justinengle-krs commented on src/models/sources/source.ts
> +  source_order_code: string;
Makes sense, will sort out

2023-04-04 09:50 UTC, matthampton-stock2shop commented on src/models/sources/source.ts
> +  source_order_code: string;
@justinengle-krs Could we remove these properties from the source model, since they are now in the new one?

2023-04-04 09:52 UTC, matthampton-stock2shop commented on src/stories/routes/85-Order.stories.svelte
> +<script lang="ts">
Hi @justinengle-krs .. I think this second comment on chromatic is still relevant:

"Could we add an example where the customer create date is not undefined"

https://www.chromatic.com/test?appId=63ef6cddab1dec384359e1cd&id=642425e4af7fb60f02bb683b

2023-04-04 10:26 UTC, justinengle-krs commented on src/models/sources/source.ts
> +  source_order_code: string;
Sorted

2023-04-04 10:26 UTC, justinengle-krs commented on src/stories/routes/85-Order.stories.svelte
> +<script lang="ts">
https://www.chromatic.com/test?appId=63ef6cddab1dec384359e1cd&id=642bfaa0c87eb930b45a0549

2023-04-04 10:26 UTC, matthampton-stock2shop approved these changes

2023-04-04 10:27 UTC, merged