Justin krs/order fulfillment modal
stock2shop/console_v2 pull request #95
Opened 2023-04-12 10:56 UTC by justinengle-krs

Fulfillment Modal

Zeplin:

![image](https://user-images.githubusercontent.com/125956275/231433742-01503da5-5c5a-4513-a849-7423f6c657bc.png)

Implementation:
![image](https://user-images.githubusercontent.com/125956275/231435434-08a0b74f-816e-494c-bce0-7222dcd8d347.png)

2023-04-12 12:54 UTC, casperlotter submitted a review, later dismissed

2023-04-19 08:47 UTC, matthampton-stock2shop commented
https://www.chromatic.com/build?appId=63ef6cddab1dec384359e1cd&number=46

2023-04-19 10:07 UTC, matthampton-stock2shop requested changes

2023-04-19 10:07 UTC, matthampton-stock2shop commented on src/components/input/Dropdown.svelte
> +      <option value={valueProperty ? option[valueProperty] : option} disabled={option.disabled ?? false} selected={!value && i == 0}>
Do we always want the first item to display as selected if there isn't a value? (this feels like something that would be better to do in the place where the dropdown component is created (i.e. actually set the value to the correct default there)

2023-04-19 10:07 UTC, matthampton-stock2shop commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
These seem like view properties to me (or functions) - rather than editable model data properties... Thoughts?

2023-04-19 10:07 UTC, matthampton-stock2shop commented on src/models/orders/order-detail.ts
> +  validateOrder(): { valid: boolean; error: string } {
It looks to me like this function is specifically about fulfullments (rather than a general-purpose order validation function)... Would you mind renaming it to me make it a bit more specific?

2023-04-19 10:57 UTC, justinengle-krs commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
To me it makes sense for the model to own this logic?  Almost like a computed field?
I can almost see these coming from the API. The usage later seems intuitive as well. 

```const itemsToFulfill = systemOrder.line_items
      .filter((l) => l.qty_to_fulfill > 0)
      .map(
        (l) =>
          new FulfillmentOrderLineItem({
            price: l.price,
            qty: l.qty_to_fulfill,
            title: l.title,
            sku: l.sku,
          })
      );
```

would you prefer something like


```const itemsToFulfill = systemOrder.line_items
      .filter((l) =>getQtyToFulfill(l) > 0)
      .map(
        (l) =>
          new FulfillmentOrderLineItem({
            price: l.price,
            qty: l.qty_to_fulfill,
            title: l.title,
            sku: l.sku,
          })
      );
```

2023-04-19 11:00 UTC, matthampton-stock2shop commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
I'd be fine for it to be a function on the model object (e.g. `l.getQtyAlreadyFullfilled()`) - I just don't really like it being a variable (that is just initialised to the right value - but could become wrong)

2023-04-19 11:05 UTC, justinengle-krs commented on src/components/input/Dropdown.svelte
> +      <option value={valueProperty ? option[valueProperty] : option} disabled={option.disabled ?? false} selected={!value && i == 0}>
I thought it could be convenient default behavior of the control, if its set in the view that would still work

2023-04-19 11:06 UTC, matthampton-stock2shop commented on src/components/input/Dropdown.svelte
> +      <option value={valueProperty ? option[valueProperty] : option} disabled={option.disabled ?? false} selected={!value && i == 0}>
But what if you want it to display a 'blank' state when the value is blank.. Can you do that somehow?

2023-04-19 11:08 UTC, justinengle-krs commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
Are you happy if its a getter?


  get qtyAlreadyFullfilled() {
    return this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
  }

  get qtyToFulfill() {
    return this.qty - this.qtyAlreadyFullfilled;
  }

2023-04-19 11:10 UTC, justinengle-krs commented on src/components/input/Dropdown.svelte
> +      <option value={valueProperty ? option[valueProperty] : option} disabled={option.disabled ?? false} selected={!value && i == 0}>
Thats true, let me make the change

2023-04-19 11:10 UTC, matthampton-stock2shop commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
For sure!

2023-04-19 11:11 UTC, justinengle-krs commented on src/models/orders/order-detail.ts
> +  validateOrder(): { valid: boolean; error: string } {
validateFulfillmentOrder ?

2023-04-19 11:12 UTC, matthampton-stock2shop commented on src/models/orders/order-detail.ts
> +  validateOrder(): { valid: boolean; error: string } {
Sounds fine... Thanks!

2023-04-19 11:40 UTC, justinengle-krs commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
@matthampton-stock2shop  I forgot we do bind to qtyToFulfill on the modal, for each line item input.
Is that correct?

2023-04-19 11:41 UTC, justinengle-krs commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
This field 

![image](https://user-images.githubusercontent.com/125956275/233064027-efda04f3-656a-4515-9f1f-6915ff2d9658.png)

2023-04-19 11:42 UTC, justinengle-krs commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
Which we then post on the 'Fulfill Order'. Which means this field at least would need to be a property on the model

2023-04-19 11:46 UTC, matthampton-stock2shop commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
Does that make sense to you?

2023-04-19 11:51 UTC, justinengle-krs commented on src/models/orders/line-item.ts
> +    this.qty_already_fulfilled = this.fulfillments.reduce((sum, f) => sum + Number(f.qty), 0);
Yes, see latest commit. Happy with that?

2023-04-19 11:56 UTC, matthampton-stock2shop approved these changes

2023-04-19 11:57 UTC, merged